# ecological-agent-skills / Copyright (C) 2026 Francisco Diego Barros Barata
# SPDX-License-Identifier: GPL-3.0-or-later

# Usage: Rscript baci_analysis.R <baci_data.csv> <output_dir> [response_col] [random_effects]
# BACI mixed-effects model for ecological impact assessment
# Usage: Rscript baci_analysis.R <data_csv> <response_var> <output_dir>
# Requires: glmmTMB, emmeans, ggplot2, dplyr

# ── Inline logger ─────────────────────────────────────────────────────────────
SKILL_NAME <- "ecological-impact-assessment"
.log_ts  <- function() format(Sys.time(), "[%Y-%m-%d %H:%M:%S]")
log_info <- function(...) message(.log_ts(), " [INFO]  ", sprintf(...))
log_warn <- function(...) message(.log_ts(), " [WARN]  ", sprintf(...))
log_error<- function(...) message(.log_ts(), " [ERROR] ", sprintf(...))
log_step <- function(n, d) log_info("-- STEP %d: %s", n, d)
log_decision <- function(v, val, why) log_info("DECISION | %s = %s | %s", v, val, why)
dir.create("logs", recursive=TRUE, showWarnings=FALSE)

suppressPackageStartupMessages({
  library(glmmTMB)
  library(emmeans)
  library(ggplot2)
  library(dplyr)
})

args         <- commandArgs(trailingOnly = TRUE)
data_file    <- ifelse(length(args) >= 1, args[1], "data/baci_data.csv")
response_var <- ifelse(length(args) >= 2, args[2], "abundance")
output_dir   <- ifelse(length(args) >= 3, args[3], "outputs/baci")
dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

log_info("Skill: %s | data_file=%s | response_var=%s | output_dir=%s",
         SKILL_NAME, data_file, response_var, output_dir)

# ── Input precondition check ──────────────────────────────────────────────────
if (!file.exists(data_file)) {
  log_error(
    "Input not found: %s\nProbable cause: wrong path or file not generated by previous step.\nCheck: whether the CSV file exists and the name is correct.\nPrevious skill: ecological-sampling-design or field collection.",
    data_file
  )
  stop("Missing: ", data_file)
}

log_step(1, "Load and validate BACI data")
dat <- tryCatch({
  read.csv(data_file)
}, error = function(e) {
  log_error(
    "Failed to read CSV: %s\nProbable cause: corrupted file or incorrect encoding.\nCheck: open the file in a text editor and verify separators.\nPrevious skill: ecological-sampling-design.",
    conditionMessage(e)
  )
  stop(e)
})

required_cols <- c("site", "period", "treatment", response_var)
missing_cols  <- setdiff(required_cols, names(dat))
if (length(missing_cols) > 0) {
  log_error(
    "Required columns missing: %s\nProbable cause: CSV does not follow the expected BACI schema.\nCheck: the file must have columns site, period, treatment and the response variable.\nPrevious skill: ecological-sampling-design.",
    paste(missing_cols, collapse = ", ")
  )
  stop("Missing columns: ", paste(missing_cols, collapse = ", "))
}

n_na <- sum(is.na(dat[[response_var]]))
if (n_na > 0) {
  log_warn("Column '%s' contains %d NA values — may be excluded by the model function.", response_var, n_na)
}

dat$period    <- factor(dat$period,    levels = c("before", "after"))
dat$treatment <- factor(dat$treatment, levels = c("control", "impact"))

n_sites  <- n_distinct(dat$site)
n_before <- sum(dat$period == "before")
n_after  <- sum(dat$period == "after")
log_info("Sites: %d | Before: %d | After: %d", n_sites, n_before, n_after)
log_decision("response_var", response_var, "response variable provided by user or default 'abundance'")
log_decision("family", "nbinom2", "negative binomial distribution appropriate for overdispersed abundance counts")

if (n_sites < 3) {
  log_warn("Only %d site(s) detected — random effects may not be estimable.", n_sites)
}

# ── Fit BACI model ────────────────────────────────────────────────────────────
log_step(2, "Ajustar modelo misto BACI (glmmTMB, nbinom2)")
formula_str <- paste(response_var, "~ period * treatment + (1|site)")
log_info("Formula: %s", formula_str)

m <- tryCatch({
  glmmTMB(as.formula(formula_str), data = dat, family = nbinom2())
}, error = function(e) {
  log_error(
    "Failed to fit glmmTMB model: %s\nProbable cause: insufficient data, mis-coded columns, or model singularity.\nCheck: number of levels per site/period and presence of excessive zeros.\nPrevious skill: ecological-sampling-design.",
    conditionMessage(e)
  )
  stop(e)
})

log_info("Model fitted successfully.")
print(summary(m))

# ── Extract BACI interaction ───────────────────────────────────────────────────
log_step(3, "Extract BACI interaction and compute effect on original scale")
coef_table <- tryCatch({
  as.data.frame(coef(summary(m))$cond)
}, error = function(e) {
  log_error(
    "Failed to extrair coeficientes do modelo: %s\nProbable cause: modelo nao convergiu ou estrutura inesperada.\nCheck: inspecione summary(m) manualmente.\nPrevious skill: [none].",
    conditionMessage(e)
  )
  stop(e)
})

baci_row <- grep("period.*treatment|treatment.*period", rownames(coef_table))

if (length(baci_row) > 0) {
  baci_est <- coef_table[baci_row, ]
  log_info("=== Interacao BACI ===")
  print(baci_est)
  effect_multiplicative <- round(exp(baci_est[, "Estimate"]), 3)
  log_info("Efeito na escala original (multiplicativo): %s", paste(effect_multiplicative, collapse = ", "))
  tryCatch({
    write.csv(baci_est, file.path(output_dir, "baci_results.csv"))
    log_info("baci_results.csv saved in: %s", output_dir)
  }, error = function(e) {
    log_error(
      "Failed to salvar baci_results.csv: %s\nProbable cause: permissao negada ou disco cheio.\nCheck: permissoes do output directory.\nPrevious skill: [none].",
      conditionMessage(e)
    )
    stop(e)
  })
} else {
  log_warn("BACI interaction term (period:treatment) not found in coefficients table.")
}

# ── Before/After plot ──────────────────────────────────────────────────────────
log_step(4, "Gerar grafico BACI (controle vs impacto, antes vs depois)")
tryCatch({
  p_baci <- dat |>
    group_by(period, treatment) |>
    summarise(mean_y = mean(.data[[response_var]], na.rm = TRUE),
              se_y   = sd(.data[[response_var]], na.rm = TRUE) / sqrt(n()),
              .groups = "drop") |>
    ggplot(aes(x = period, y = mean_y, colour = treatment, group = treatment)) +
    geom_line(linewidth = 1) +
    geom_point(size = 3) +
    geom_errorbar(aes(ymin = mean_y - se_y, ymax = mean_y + se_y), width = 0.1) +
    scale_colour_manual(values = c(control = "#2166ac", impact = "#d6604d")) +
    labs(y = response_var, title = "BACI: Control vs Impact") +
    theme_bw()
  ggsave(file.path(output_dir, "baci_plot.png"), p_baci, width = 6, height = 5, dpi = 150)
  log_info("baci_plot.png saved in: %s", output_dir)
}, error = function(e) {
  log_error(
    "Failed to generate ou salvar grafico BACI: %s\nProbable cause: insufficient data para sumarizacao ou directory sem permissao de escrita.\nCheck: presenca de pelo menos um registro por combinacao period/treatment.\nPrevious skill: [none].",
    conditionMessage(e)
  )
  stop(e)
})

log_info("Analise BACI completed. Outputs in: %s", output_dir)
