# ecological-agent-skills / Copyright (C) 2026 Francisco Diego Barros Barata
# SPDX-License-Identifier: GPL-3.0-or-later

# Usage: Rscript run_ensemble_sdm.R <params_yaml> <output_dir>
# Fit MaxEnt + BRT + RF ensemble SDM with spatial block cross-validation.
# Requires: terra, sf, maxnet, gbm, randomForest, blockCV, dismo, yaml, ggplot2

# ── Inline logger ─────────────────────────────────────────────────────────────
SKILL_NAME <- "species-distribution-modeling"
.log_ts   <- function() format(Sys.time(), "[%Y-%m-%d %H:%M:%S]")
log_info  <- function(...) message(.log_ts(), " [INFO]  ", sprintf(...))
log_warn  <- function(...) message(.log_ts(), " [WARN]  ", sprintf(...))
log_error <- function(...) message(.log_ts(), " [ERROR] ", sprintf(...))
log_step  <- function(n, d) log_info("-- STEP %d: %s", n, d)
log_decision <- function(v, val, why) log_info("DECISION | %s = %s | %s", v, val, why)
dir.create("logs", recursive = TRUE, showWarnings = FALSE)

suppressPackageStartupMessages({
  library(terra); library(sf)
  library(maxnet); library(gbm); library(randomForest)
  library(yaml); library(ggplot2)
})

# Null-coalescing helper
`%||%` <- function(a, b) if (!is.null(a)) a else b

# ── 1. Arguments and parameters ───────────────────────────────────────────────
log_step(1, "Parse arguments and load YAML parameters")
args       <- commandArgs(trailingOnly = TRUE)
params_f   <- ifelse(length(args) >= 1, args[1], "params.yaml")
output_dir <- ifelse(length(args) >= 2, args[2], "outputs/sdm")

log_info("Script: run_ensemble_sdm.R | Skill: %s", SKILL_NAME)
log_info("Params file : %s", params_f)
log_info("Output dir  : %s", output_dir)

if (!file.exists(params_f)) {
  log_error(
    "Input not found: %s\nProbable cause: params.yaml not generated by previous step.\nCheck output of: species-distribution-modeling (tune_maxnet or prepare_future_layers)\nPrevious skill: species-distribution-modeling",
    params_f
  )
  stop("Missing: ", params_f)
}

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
log_info("Output directory ready: %s", output_dir)

p <- tryCatch({
  yaml::read_yaml(params_f)
}, error = function(e) {
  log_error(
    "Failed to read YAML '%s': %s\nProbable cause: malformed YAML or incorrect encoding.\nCheck YAML syntax.\nPrevious skill: species-distribution-modeling",
    params_f, conditionMessage(e)
  )
  stop(e)
})

set.seed(p$random_seeds$global %||% 42)
log_decision("random_seed", p$random_seeds$global %||% 42, "global seed from params.yaml for full reproducibility")
log_decision("algorithms",  paste(p$modeling$algorithms, collapse = ","), "algorithms defined in params.yaml$modeling$algorithms")
log_decision("cv_method",   p$modeling$cv_method   %||% "spatial_block", "cross-validation method from params.yaml")
log_decision("cv_folds",    p$modeling$cv_folds    %||% 5,               "number of folds from params.yaml")

# ── 2. Load occurrence and background data ─────────────────────────────────────
log_step(2, "Load occurrence and background data")

occ_path <- p$data$occurrences      %||% "data/processed/occ_thinned.csv"
bg_path  <- p$data$background       %||% "data/processed/background.csv"
pred_tif <- p$data$predictors_stack %||% "data/processed/predictors_stack.tif"

for (f in c(occ_path, bg_path, pred_tif)) {
  if (!file.exists(f)) {
    log_error(
      "Required file not found: %s\nProbable cause: ecological-data-foundation or geoprocessing-for-ecology not yet executed.\nPrevious skill: ecological-data-foundation",
      f
    )
    stop("Missing required input: ", f)
  }
}

occ_df <- read.csv(occ_path)
bg_df  <- read.csv(bg_path)
stack  <- terra::rast(pred_tif)

log_info("Occurrences loaded : %d records | %d columns", nrow(occ_df), ncol(occ_df))
log_info("Background loaded  : %d records | %d columns", nrow(bg_df),  ncol(bg_df))
log_info("Predictor stack    : %d layers | Extent: %.2f %.2f %.2f %.2f",
         terra::nlyr(stack), terra::ext(stack)[1], terra::ext(stack)[2],
         terra::ext(stack)[3], terra::ext(stack)[4])

# Identify coordinate columns
lon_col <- intersect(c("decimalLongitude", "longitude", "lon", "x"), names(occ_df))[1]
lat_col <- intersect(c("decimalLatitude",  "latitude",  "lat", "y"), names(occ_df))[1]
bg_lon  <- intersect(c("decimalLongitude", "longitude", "lon", "x"), names(bg_df))[1]
bg_lat  <- intersect(c("decimalLatitude",  "latitude",  "lat", "y"), names(bg_df))[1]

if (is.na(lon_col) || is.na(lat_col)) {
  log_error(
    "Coordinate columns not found in occurrence CSV.\nExpected: decimalLongitude/decimalLatitude (or longitude/latitude, lon/lat, x/y).\nColumns present: %s\nProbable cause: CSV not processed by clean_occurrences.\nPrevious skill: ecological-data-foundation",
    paste(names(occ_df), collapse = ", ")
  )
  stop("Cannot find coordinate columns in occurrence CSV.")
}

log_info("Occurrence coords: lon='%s', lat='%s'", lon_col, lat_col)
log_info("Background coords: lon='%s', lat='%s'", bg_lon,  bg_lat)

# ── 3. Select predictor layers ─────────────────────────────────────────────────
log_step(3, "Select predictor layers")

sel_pred_f <- p$data$selected_predictors %||%
              file.path(dirname(output_dir), "selected_predictors.txt")

if (file.exists(sel_pred_f)) {
  selected_preds <- readLines(sel_pred_f)
  selected_preds <- trimws(selected_preds[nchar(trimws(selected_preds)) > 0])
  log_decision("predictor_source", sel_pred_f, "selected_predictors.txt found; using VIF-filtered set")
} else {
  selected_preds <- names(stack)
  log_warn("selected_predictors.txt not found at '%s'. Using all %d stack layers.", sel_pred_f, terra::nlyr(stack))
  log_decision("predictor_source", "all layers", "no selected_predictors.txt found; using full stack")
}

selected_preds <- intersect(selected_preds, names(stack))
if (length(selected_preds) == 0) {
  log_error(
    "No matching predictors between selection list and stack layers.\nStack layers: %s\nPrevious skill: geoprocessing-for-ecology",
    paste(names(stack), collapse = ", ")
  )
  stop("No valid predictors found in stack.")
}

stack_sel <- stack[[selected_preds]]
log_info("Predictors selected: %d  (%s)", length(selected_preds),
         paste(selected_preds, collapse = ", "))

# ── 4. Extract environmental values ────────────────────────────────────────────
log_step(4, "Extract environmental values at occurrence and background points")

occ_pts_df <- occ_df[, c(lon_col, lat_col)]
bg_pts_df  <- bg_df[, c(bg_lon, bg_lat)]
names(occ_pts_df) <- c("x", "y")
names(bg_pts_df)  <- c("x", "y")

occ_env <- as.data.frame(terra::extract(stack_sel, as.matrix(occ_pts_df)))[, -1, drop = FALSE]
bg_env  <- as.data.frame(terra::extract(stack_sel, as.matrix(bg_pts_df)))[,  -1, drop = FALSE]

occ_ok  <- complete.cases(occ_env)
bg_ok   <- complete.cases(bg_env)

occ_env     <- occ_env[occ_ok,     , drop = FALSE]
occ_pts_df  <- occ_pts_df[occ_ok,  , drop = FALSE]
bg_env      <- bg_env[bg_ok,       , drop = FALSE]
bg_pts_df   <- bg_pts_df[bg_ok,    , drop = FALSE]

log_info("Occurrences after NA removal: %d", nrow(occ_env))
log_info("Background after NA removal : %d", nrow(bg_env))

n_occ_min <- p$decision_points$n_occurrences_min %||% 10
if (nrow(occ_env) < n_occ_min) {
  log_error(
    "Too few valid occurrences (%d) after NA removal. Minimum required: %d.\nProbable cause: occurrence points outside predictor raster extent.\nPrevious skill: geoprocessing-for-ecology",
    nrow(occ_env), n_occ_min
  )
  stop("Insufficient occurrences for modeling.")
}

# Combined training data frame (pa=1 presences, pa=0 background)
train_df <- rbind(
  cbind(pa = 1L, occ_env),
  cbind(pa = 0L, bg_env)
)
log_info("Training matrix: %d presences + %d background = %d total",
         nrow(occ_env), nrow(bg_env), nrow(train_df))

# ── 5. Spatial block cross-validation ─────────────────────────────────────────
log_step(5, "Spatial block cross-validation setup")
cv_k <- p$modeling$cv_folds %||% 5

log_decision("cv_method", "spatial_block",
             "blockCV::cv_spatial avoids AUC inflation from spatial autocorrelation (Valavi et al. 2019)")
log_decision("cv_folds", cv_k, "k folds from params.yaml")

all_pts <- rbind(
  data.frame(occ_pts_df, pa = 1L),
  data.frame(bg_pts_df,  pa = 0L)
)
all_sf <- sf::st_as_sf(all_pts, coords = c("x", "y"), crs = 4326)

cv_folds <- tryCatch({
  blockCV::cv_spatial(
    x        = all_sf,
    column   = "pa",
    r        = stack_sel[[1]],
    k        = cv_k,
    hexagon  = FALSE,
    progress = FALSE
  )
}, error = function(e) {
  log_warn(
    "blockCV::cv_spatial failed: %s\nFalling back to random %d-fold CV.\nTo use spatial CV: install.packages('blockCV')",
    conditionMessage(e), cv_k
  )
  log_decision("cv_fallback", "random_kfold",
               "blockCV unavailable or insufficient spatial extent; using random k-fold")
  n <- nrow(all_pts)
  fold_ids <- sample(rep(seq_len(cv_k), length.out = n))
  list(
    folds_list = lapply(seq_len(cv_k), function(i) list(
      train = which(fold_ids != i),
      test  = which(fold_ids == i)
    ))
  )
})

log_info("Cross-validation folds ready: %d folds", cv_k)

# ── 6. Hyperparameters ────────────────────────────────────────────────────────
log_step(6, "Resolve model hyperparameters")

maxnet_rm <- p$hyperparameters$maxnet$regularization_multiplier %||% 1.0
if (length(maxnet_rm) > 1) maxnet_rm <- maxnet_rm[ceiling(length(maxnet_rm) / 2)]
maxnet_fc <- p$hyperparameters$maxnet$feature_classes %||% "LQH"

brt_lr    <- p$hyperparameters$brt$learning_rate    %||% 0.01
brt_trees <- p$hyperparameters$brt$n_trees          %||% 500
brt_depth <- p$hyperparameters$brt$tree_complexity  %||% 3
rf_ntree  <- p$hyperparameters$rf$n_trees           %||% 500

log_decision("maxnet_rm",  maxnet_rm,  "regularization multiplier; use tuned value from tune_maxnet.R when available")
log_decision("maxnet_fc",  maxnet_fc,  "feature class combination for MaxEnt")
log_decision("brt_lr",     brt_lr,     "BRT learning rate from params.yaml or default 0.01")
log_decision("brt_trees",  brt_trees,  "BRT number of trees from params.yaml or default 500")
log_decision("brt_depth",  brt_depth,  "BRT tree complexity from params.yaml or default 3")
log_decision("rf_ntree",   rf_ntree,   "RF number of trees from params.yaml or default 500")

algorithms <- tolower(p$modeling$algorithms %||% c("maxent", "brt", "rf"))
log_info("Algorithms: %s", paste(algorithms, collapse = ", "))

# ── 7. Performance helpers ─────────────────────────────────────────────────────
compute_auc <- function(pred_1, pred_0) {
  n1 <- length(pred_1); n0 <- length(pred_0)
  if (n1 == 0 || n0 == 0) return(NA_real_)
  (sum(outer(pred_1, pred_0, ">")) + 0.5 * sum(outer(pred_1, pred_0, "=="))) / (n1 * n0)
}

compute_tss <- function(pred_1, pred_0) {
  thresholds <- sort(unique(c(pred_1, pred_0)))
  if (length(thresholds) == 0) return(NA_real_)
  tss_vals <- vapply(thresholds, function(th) {
    mean(pred_1 >= th) + mean(pred_0 < th) - 1
  }, numeric(1))
  max(tss_vals, na.rm = TRUE)
}

# ── 8. Cross-validation loop ──────────────────────────────────────────────────
log_step(8, "Fit models with cross-validation (MaxEnt, BRT, RF)")

folds_list <- cv_folds$folds_list
cv_results <- vector("list", cv_k)

for (fold_i in seq_len(cv_k)) {
  log_info("Fold %d/%d ...", fold_i, cv_k)

  tr_idx <- folds_list[[fold_i]]$train
  te_idx <- folds_list[[fold_i]]$test

  tr <- train_df[tr_idx, , drop = FALSE]
  te <- train_df[te_idx, , drop = FALSE]
  te_pa  <- te$pa
  tr_env <- tr[, -1, drop = FALSE]
  te_env <- te[, -1, drop = FALSE]

  preds_fold <- list()

  # MaxEnt
  if (any(c("maxent", "maxnet") %in% algorithms)) {
    mx <- tryCatch(
      maxnet::maxnet(p = tr$pa, data = tr_env, regmult = maxnet_rm,
                     f = maxnet::maxnet.formula(tr$pa, tr_env,
                                                classes = tolower(maxnet_fc))),
      error = function(e) {
        log_warn("MaxEnt fold %d failed: %s", fold_i, conditionMessage(e)); NULL
      }
    )
    if (!is.null(mx))
      preds_fold$maxent <- as.numeric(predict(mx, te_env, type = "cloglog"))
  }

  # BRT
  if (any(c("brt", "gbm") %in% algorithms)) {
    brt <- tryCatch(
      gbm::gbm(pa ~ ., data = tr, distribution = "bernoulli",
                n.trees = brt_trees, interaction.depth = brt_depth,
                shrinkage = brt_lr, bag.fraction = 0.75, verbose = FALSE),
      error = function(e) {
        log_warn("BRT fold %d failed: %s", fold_i, conditionMessage(e)); NULL
      }
    )
    if (!is.null(brt))
      preds_fold$brt <- as.numeric(predict(brt, te, n.trees = brt_trees, type = "response"))
  }

  # Random Forest
  if (any(c("rf", "randomforest") %in% algorithms)) {
    rf_tr <- tr; rf_tr$pa <- as.factor(rf_tr$pa)
    rf <- tryCatch(
      randomForest::randomForest(pa ~ ., data = rf_tr, ntree = rf_ntree),
      error = function(e) {
        log_warn("RF fold %d failed: %s", fold_i, conditionMessage(e)); NULL
      }
    )
    if (!is.null(rf))
      preds_fold$rf <- as.numeric(predict(rf, te, type = "prob")[, "1"])
  }

  if (length(preds_fold) > 0) {
    pred_mat <- do.call(cbind, preds_fold)

    # Compute per-algorithm AUC for this fold
    fold_aucs <- vapply(names(preds_fold), function(a) {
      compute_auc(preds_fold[[a]][te_pa == 1], preds_fold[[a]][te_pa == 0])
    }, numeric(1))
    fold_aucs[is.na(fold_aucs)] <- 0

    # AUC-weighted ensemble (fall back to equal weights if all AUCs are zero)
    if (sum(fold_aucs) > 0) {
      w <- fold_aucs / sum(fold_aucs)
      ens_pred <- as.numeric(pred_mat %*% w)
    } else {
      ens_pred <- rowMeans(pred_mat, na.rm = TRUE)
    }

    p1 <- ens_pred[te_pa == 1]
    p0 <- ens_pred[te_pa == 0]

    cv_results[[fold_i]] <- data.frame(
      fold    = fold_i,
      n_train = nrow(tr),
      n_test  = nrow(te),
      auc_maxent = if (!is.null(preds_fold$maxent))
        compute_auc(preds_fold$maxent[te_pa==1], preds_fold$maxent[te_pa==0]) else NA_real_,
      auc_brt    = if (!is.null(preds_fold$brt))
        compute_auc(preds_fold$brt[te_pa==1],    preds_fold$brt[te_pa==0])    else NA_real_,
      auc_rf     = if (!is.null(preds_fold$rf))
        compute_auc(preds_fold$rf[te_pa==1],     preds_fold$rf[te_pa==0])     else NA_real_,
      auc_ensemble = compute_auc(p1, p0),
      tss_ensemble = compute_tss(p1, p0)
    )
  } else {
    log_warn("No models succeeded in fold %d.", fold_i)
    cv_results[[fold_i]] <- data.frame(fold = fold_i, n_train = nrow(tr), n_test = nrow(te),
      auc_maxent = NA, auc_brt = NA, auc_rf = NA, auc_ensemble = NA, tss_ensemble = NA)
  }
}

cv_df <- do.call(rbind, cv_results)
write.csv(cv_df, file.path(output_dir, "cv_performance.csv"), row.names = FALSE)
log_info("Written: cv_performance.csv")
log_info("CV AUC mean: %.3f (SD: %.3f) | TSS mean: %.3f (SD: %.3f)",
         mean(cv_df$auc_ensemble, na.rm = TRUE), sd(cv_df$auc_ensemble, na.rm = TRUE),
         mean(cv_df$tss_ensemble, na.rm = TRUE), sd(cv_df$tss_ensemble, na.rm = TRUE))

# ── Compute AUC-based ensemble weights from CV results ────────────────────────
algo_aucs <- c(
  maxent = mean(cv_df$auc_maxent, na.rm = TRUE),
  brt    = mean(cv_df$auc_brt,    na.rm = TRUE),
  rf     = mean(cv_df$auc_rf,     na.rm = TRUE)
)
algo_aucs <- algo_aucs[!is.na(algo_aucs)]
if (length(algo_aucs) > 0 && sum(algo_aucs) > 0) {
  auc_weights <- algo_aucs / sum(algo_aucs)
} else {
  auc_weights <- setNames(rep(1 / length(active_algos), length(active_algos)), active_algos)
}
log_decision("ensemble_weighting", "AUC-weighted",
             "Weights proportional to mean CV AUC per algorithm — avoids mixing incompatible output scales equally")
log_info("Ensemble weights: %s",
         paste(sprintf("%s=%.3f", names(auc_weights), auc_weights), collapse = ", "))

auc_mean <- mean(cv_df$auc_ensemble, na.rm = TRUE)
auc_min  <- p$decision_points$auc_min_acceptable %||% 0.7
if (!is.na(auc_mean) && auc_mean < auc_min) {
  log_warn(
    "Ensemble AUC (%.3f) is below the minimum acceptable threshold (%.2f).\nConsider: revising predictors, expanding calibration area, or reviewing occurrence data quality.",
    auc_mean, auc_min
  )
}

# ── 9. Final models on full training data ─────────────────────────────────────
log_step(9, "Fit final models on full training data")

final_models <- list()

if (any(c("maxent", "maxnet") %in% algorithms)) {
  log_info("Fitting final MaxEnt (RM=%.1f, FC=%s)...", maxnet_rm, maxnet_fc)
  final_models$maxent <- tryCatch(
    maxnet::maxnet(p = train_df$pa, data = train_df[, -1, drop = FALSE],
                   regmult = maxnet_rm,
                   f = maxnet::maxnet.formula(train_df$pa, train_df[, -1, drop = FALSE],
                                              classes = tolower(maxnet_fc))),
    error = function(e) {
      log_error("Final MaxEnt fit failed: %s\nProbable cause: insufficient presence records or predictor collinearity.\nPrevious skill: species-distribution-modeling", conditionMessage(e))
      NULL
    }
  )
}

if (any(c("brt", "gbm") %in% algorithms)) {
  log_info("Fitting final BRT (n_trees=%d, lr=%.4f, depth=%d)...", brt_trees, brt_lr, brt_depth)
  final_models$brt <- tryCatch(
    gbm::gbm(pa ~ ., data = train_df, distribution = "bernoulli",
              n.trees = brt_trees, interaction.depth = brt_depth,
              shrinkage = brt_lr, bag.fraction = 0.75, verbose = FALSE),
    error = function(e) {
      log_error("Final BRT fit failed: %s\nPrevious skill: species-distribution-modeling",
                conditionMessage(e)); NULL
    }
  )
}

if (any(c("rf", "randomforest") %in% algorithms)) {
  log_info("Fitting final RF (ntree=%d)...", rf_ntree)
  rf_full <- train_df; rf_full$pa <- as.factor(rf_full$pa)
  final_models$rf <- tryCatch(
    randomForest::randomForest(pa ~ ., data = rf_full, ntree = rf_ntree, importance = TRUE),
    error = function(e) {
      log_error("Final RF fit failed: %s\nPrevious skill: species-distribution-modeling",
                conditionMessage(e)); NULL
    }
  )
}

active_algos <- names(Filter(Negate(is.null), final_models))
if (length(active_algos) == 0) {
  log_error("All final model fits failed.\nProbable cause: package installation issues or data format errors.\nPrevious skill: species-distribution-modeling")
  stop("No models fitted successfully.")
}
log_info("Final models fitted: %s", paste(active_algos, collapse = ", "))

saveRDS(list(models = final_models, auc_weights = auc_weights),
        file.path(output_dir, "ensemble_models.rds"))
log_info("Written: ensemble_models.rds (with AUC weights)")

# ── 10. Predict over study area ───────────────────────────────────────────────
log_step(10, "Predict ensemble suitability over study area raster")

predict_raster <- function(model, stk, algo) {
  tryCatch({
    switch(algo,
      maxent = terra::predict(stk, model, type = "cloglog", na.rm = TRUE),
      brt    = terra::predict(stk, model, n.trees = brt_trees, type = "response", na.rm = TRUE),
      rf     = terra::predict(stk, model, type = "prob", index = 2L, na.rm = TRUE)
    )
  }, error = function(e) {
    log_warn("Raster prediction failed for %s: %s", algo, conditionMessage(e)); NULL
  })
}

pred_rasters <- Filter(Negate(is.null),
  setNames(lapply(active_algos, function(a) predict_raster(final_models[[a]], stack_sel, a)),
           active_algos))

if (length(pred_rasters) == 0) {
  log_error("All raster predictions failed.\nProbable cause: terra::predict incompatibility with model object type.\nPrevious skill: species-distribution-modeling")
  stop("No valid raster predictions produced.")
}

pred_stack <- terra::rast(pred_rasters)
w_raster   <- auc_weights[names(pred_rasters)]
w_raster   <- w_raster / sum(w_raster)  # re-normalise in case an algo failed
ens_mean   <- terra::app(pred_stack, fun = function(x) weighted.mean(x, w_raster, na.rm = TRUE))
ens_sd     <- if (terra::nlyr(pred_stack) > 1)
                terra::app(pred_stack, sd, na.rm = TRUE) else
                ens_mean * 0

terra::writeRaster(ens_mean, file.path(output_dir, "suitability_current.tif"), overwrite = TRUE)
terra::writeRaster(ens_sd,   file.path(output_dir, "ensemble_sd.tif"),         overwrite = TRUE)
log_info("Written: suitability_current.tif")
log_info("Written: ensemble_sd.tif")

# ── 11. Threshold and binary map ──────────────────────────────────────────────
log_step(11, "Apply P10 threshold and create binary suitability map")
log_decision("threshold_method", "P10",
             "10th percentile of suitability at presence locations — conservative and widely used in SDM")

occ_suit <- terra::extract(ens_mean, as.matrix(occ_pts_df))[, 2]
occ_suit <- occ_suit[!is.na(occ_suit)]

p10_threshold <- if (length(occ_suit) >= 5) {
  quantile(occ_suit, 0.10, na.rm = TRUE)
} else {
  log_warn("Too few valid suitability values at occurrence locations (%d). Using 0.5 as fallback.", length(occ_suit))
  0.5
}

log_info("P10 threshold: %.4f", p10_threshold)

binary_map <- terra::ifel(ens_mean >= p10_threshold, 1L, 0L)
terra::writeRaster(binary_map, file.path(output_dir, "suitability_binary.tif"),
                   overwrite = TRUE, datatype = "INT1U")
log_info("Written: suitability_binary.tif")

# Suitable area
cell_res_deg  <- mean(terra::res(ens_mean))
cell_area_km2 <- (cell_res_deg * 111.32)^2
suit_cells    <- sum(terra::values(binary_map) == 1L, na.rm = TRUE)
total_cells   <- sum(!is.na(terra::values(binary_map)))
suitable_km2  <- suit_cells   * cell_area_km2
total_km2     <- total_cells  * cell_area_km2
pct_suitable  <- 100 * suit_cells / total_cells
mean_suit     <- mean(terra::values(ens_mean), na.rm = TRUE)

summary_df <- data.frame(
  scenario          = "current",
  threshold_method  = "P10",
  threshold_value   = round(p10_threshold, 4),
  total_area_km2    = round(total_km2,    1),
  suitable_area_km2 = round(suitable_km2, 1),
  pct_suitable      = round(pct_suitable, 2),
  mean_suitability  = round(mean_suit,    4)
)
write.csv(summary_df, file.path(output_dir, "prediction_summary.csv"), row.names = FALSE)
log_info("Written: prediction_summary.csv")
log_info("Suitable area: %.0f km2 (%.2f%% of study extent)", suitable_km2, pct_suitable)

# ── 12. Variable importance ────────────────────────────────────────────────────
log_step(12, "Compute and save variable importance")

varimp_rows <- list()

if (!is.null(final_models$rf)) {
  rf_imp <- as.data.frame(randomForest::importance(final_models$rf, type = 1))
  varimp_rows$rf <- data.frame(
    variable  = rownames(rf_imp),
    algorithm = "RandomForest",
    importance = rf_imp[, 1]
  )
}

if (!is.null(final_models$brt)) {
  brt_imp <- gbm::summary.gbm(final_models$brt, plotit = FALSE)
  varimp_rows$brt <- data.frame(
    variable  = brt_imp$var,
    algorithm = "BRT",
    importance = brt_imp$rel.inf
  )
}

if (length(varimp_rows) > 0) {
  varimp_df   <- do.call(rbind, varimp_rows)
  varimp_path <- file.path(output_dir, "variable_importance.csv")
  write.csv(varimp_df, varimp_path, row.names = FALSE)
  log_info("Written: %s", varimp_path)

  rf_top <- varimp_df[varimp_df$algorithm == "RandomForest", ]
  rf_top <- rf_top[order(rf_top$importance, decreasing = TRUE), ][seq_len(min(5, nrow(rf_top))), ]
  log_info("Top predictors (RF): %s", paste(rf_top$variable, collapse = ", "))
} else {
  log_warn("Variable importance not computed (RF not fitted).")
}

# ── 13. Response curves (partial dependence) ───────────────────────────────────
log_step(13, "Generate response curves (partial dependence)")

ref_model <- final_models$maxent %||% final_models$rf

if (!is.null(ref_model)) {
  log_info("Generating partial dependence curves for %d predictors...", length(selected_preds))
  ref_row <- as.data.frame(lapply(train_df[, -1, drop = FALSE], median, na.rm = TRUE))
  n_seq   <- 100

  plot_df <- do.call(rbind, lapply(selected_preds, function(pred_nm) {
    x_range <- range(train_df[[pred_nm]], na.rm = TRUE)
    x_seq   <- seq(x_range[1], x_range[2], length.out = n_seq)
    tmp     <- ref_row[rep(1L, n_seq), , drop = FALSE]
    tmp[[pred_nm]] <- x_seq
    suit <- tryCatch({
      if (!is.null(final_models$maxent))
        as.numeric(predict(final_models$maxent, tmp, type = "cloglog"))
      else
        as.numeric(predict(final_models$rf, tmp, type = "prob")[, "1"])
    }, error = function(e) rep(NA_real_, n_seq))
    data.frame(predictor = pred_nm, x = x_seq, suitability = suit)
  }))

  n_cols  <- min(3L, length(selected_preds))
  rc_plot <- ggplot(plot_df, aes(x = x, y = suitability)) +
    geom_line(colour = "#2166AC", linewidth = 0.8) +
    geom_hline(yintercept = p10_threshold, linetype = "dashed",
               colour = "firebrick", linewidth = 0.4) +
    facet_wrap(~predictor, scales = "free_x", ncol = n_cols) +
    labs(
      title    = "Response Curves — Ensemble SDM (partial dependence)",
      subtitle = sprintf("Red dashed line = P10 threshold (%.3f) | Other predictors at median",
                         p10_threshold),
      x = "Predictor value",
      y = "Ensemble suitability (0-1)"
    ) +
    scale_y_continuous(limits = c(0, 1)) +
    theme_bw(base_size = 10) +
    theme(strip.text = element_text(size = 8, face = "bold"))

  rc_path <- file.path(output_dir, "response_curves.png")
  ggplot2::ggsave(rc_path, rc_plot,
                  width  = 4 * n_cols,
                  height = 4 * ceiling(length(selected_preds) / n_cols),
                  dpi = 150, limitsize = FALSE)
  log_info("Written: %s", rc_path)
} else {
  log_warn("Response curves skipped: no MaxEnt or RF model available.")
}

# ── 14. SDM markdown report ────────────────────────────────────────────────────
log_step(14, "Write SDM report (sdm_report.md)")

species_name <- p$species %||% "unknown"

report_lines <- c(
  sprintf("# SDM Report -- *%s*", species_name),
  "",
  sprintf("**Date:** %s", format(Sys.Date(), "%Y-%m-%d")),
  sprintf("**Study area:** %s", p$study_area$description %||% "see params.yaml"),
  sprintf("**Predictors:** %s", paste(selected_preds, collapse = ", ")),
  "**Projection:** Current climate",
  "",
  "---",
  "",
  "## Occurrence Data",
  "",
  "| Item | Value |",
  "|------|-------|",
  sprintf("| Source | %s |",             p$data$source %||% "see params.yaml"),
  sprintf("| Occurrence records | %d |", nrow(occ_env)),
  sprintf("| Background points | %d |",  nrow(bg_env)),
  "",
  "---",
  "",
  "## Predictors Used",
  "",
  paste0("- ", paste(selected_preds, collapse = "\n- ")),
  "",
  "---",
  "",
  "## Model Performance (Spatial Block CV)",
  "",
  "| Metric | Ensemble |",
  "|--------|----------|",
  sprintf("| AUC mean (SD) | %.3f (%.3f) |",
          mean(cv_df$auc_ensemble, na.rm = TRUE), sd(cv_df$auc_ensemble, na.rm = TRUE)),
  sprintf("| TSS mean (SD) | %.3f (%.3f) |",
          mean(cv_df$tss_ensemble, na.rm = TRUE), sd(cv_df$tss_ensemble, na.rm = TRUE)),
  if (!is.na(mean(cv_df$auc_maxent, na.rm = TRUE)))
    sprintf("| AUC MaxEnt | %.3f |", mean(cv_df$auc_maxent, na.rm = TRUE)) else NULL,
  if (!is.na(mean(cv_df$auc_brt, na.rm = TRUE)))
    sprintf("| AUC BRT | %.3f |",    mean(cv_df$auc_brt,    na.rm = TRUE)) else NULL,
  if (!is.na(mean(cv_df$auc_rf,  na.rm = TRUE)))
    sprintf("| AUC RF | %.3f |",     mean(cv_df$auc_rf,     na.rm = TRUE)) else NULL,
  "",
  "---",
  "",
  "## Variable Importance",
  if (!is.null(varimp_rows$rf)) {
    rf_vi <- varimp_rows$rf[order(varimp_rows$rf$importance, decreasing = TRUE), ][seq_len(min(5, nrow(varimp_rows$rf))), ]
    c("", "**Top 5 (Random Forest):**", "",
      "| Rank | Variable | Importance |",
      "|------|----------|------------|",
      sprintf("| %d | %s | %.4f |", seq_len(nrow(rf_vi)), rf_vi$variable, rf_vi$importance))
  } else character(0),
  "",
  "---",
  "",
  "## Suitable Area",
  "",
  "| Metric | Value |",
  "|--------|-------|",
  "| Threshold method | P10 |",
  sprintf("| Threshold value | %.4f |",    p10_threshold),
  sprintf("| Suitable area | %.0f km² |",  suitable_km2),
  sprintf("| %% of study area | %.2f%% |", pct_suitable),
  sprintf("| Mean suitability | %.4f |",   mean_suit),
  "",
  "---",
  "",
  "## Output Files",
  "",
  "| File | Description |",
  "|------|-------------|",
  "| `suitability_current.tif` | Ensemble mean suitability (0–1) |",
  "| `suitability_binary.tif` | Binary suitable/unsuitable (P10 threshold) |",
  "| `ensemble_sd.tif` | Uncertainty across algorithms (standard deviation) |",
  "| `variable_importance.csv` | Permutation importance (RF) + relative influence (BRT) |",
  "| `response_curves.png` | Partial dependence response curves |",
  "| `cv_performance.csv` | AUC and TSS per cross-validation fold |",
  "| `prediction_summary.csv` | Suitable area statistics |",
  "| `ensemble_models.rds` | Fitted model objects with AUC weights for downstream projection |",
  "",
  "---",
  "",
  "## Methods",
  "",
  sprintf("- **Algorithms:** %s", paste(active_algos, collapse = ", ")),
  "- **Ensemble:** arithmetic mean of per-algorithm suitability predictions",
  "- **Cross-validation:** spatial block CV (blockCV::cv_spatial; Valavi et al. 2019)",
  "- **Threshold:** P10 (10th percentile of ensemble suitability at presence locations)",
  "- **Variable importance:** permutation importance (RF), relative influence (BRT)",
  "- **Response curves:** partial dependence (all other predictors fixed at median)"
)

report_lines <- report_lines[!sapply(report_lines, is.null)]
writeLines(report_lines, file.path(output_dir, "sdm_report.md"))
log_info("Written: sdm_report.md")

# ── 15. Final summary ──────────────────────────────────────────────────────────
log_step(15, "Pipeline complete")
log_info("========== SDM ENSEMBLE PIPELINE COMPLETE ==========")
log_info("Species       : %s",    species_name)
log_info("Algorithms    : %s",    paste(active_algos, collapse = ", "))
log_info("CV AUC        : %.3f +/- %.3f",
         mean(cv_df$auc_ensemble, na.rm = TRUE), sd(cv_df$auc_ensemble, na.rm = TRUE))
log_info("CV TSS        : %.3f +/- %.3f",
         mean(cv_df$tss_ensemble, na.rm = TRUE), sd(cv_df$tss_ensemble, na.rm = TRUE))
log_info("Suitable area : %.0f km2 (%.2f%% of extent)", suitable_km2, pct_suitable)
log_info("P10 threshold : %.4f", p10_threshold)
log_info("Output dir    : %s",   output_dir)
log_info("=====================================================")
