# ecological-agent-skills / Copyright (C) 2026 Francisco Diego Barros Barata
# SPDX-License-Identifier: GPL-3.0-or-later

# Usage: Rscript clean_occurrences.R <raw_occurrences.csv> <output_dir> [country_code]

# ── Inline logger ─────────────────────────────────────────────────────────────
SKILL_NAME <- "ecological-data-foundation"
.log_ts  <- function() format(Sys.time(), "[%Y-%m-%d %H:%M:%S]")
log_info <- function(...) message(.log_ts(), " [INFO]  ", sprintf(...))
log_warn <- function(...) message(.log_ts(), " [WARN]  ", sprintf(...))
log_error<- function(...) message(.log_ts(), " [ERROR] ", sprintf(...))
log_step <- function(n, d) log_info("-- STEP %d: %s", n, d)
log_decision <- function(v, val, why) log_info("DECISION | %s = %s | %s", v, val, why)
dir.create("logs", recursive=TRUE, showWarnings=FALSE)

# Standard occurrence cleaning pipeline
# Usage: Rscript clean_occurrences.R <input_csv> <output_dir>
# Requires: dplyr, readr, CoordinateCleaner, taxize, janitor

suppressPackageStartupMessages({
  library(dplyr)
  library(readr)
  library(CoordinateCleaner)
  library(janitor)
})

args <- commandArgs(trailingOnly = TRUE)
input_file  <- ifelse(length(args) >= 1, args[1], "data/raw/occurrences.csv")
output_dir  <- ifelse(length(args) >= 2, args[2], "data/processed")

log_info("Script: clean_occurrences.R | Skill: %s", SKILL_NAME)
log_info("Input file : %s", input_file)
log_info("Output dir : %s", output_dir)

# ── Input precondition check ──────────────────────────────────────────────────
if (!file.exists(input_file)) {
  log_error(
    "Input not found: %s\nProbable cause: file not generated by the previous step.\nCheck the output of: ecological-data-foundation (download_from_gbif)\nPrevious skill: ecological-data-foundation",
    input_file
  )
  stop("Missing: ", input_file)
}

dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)

log_decision("input_file", input_file, "path provided as args[1] or default")
log_decision("output_dir", output_dir, "path provided as args[2] or default")

# ── 1. Ingest ──────────────────────────────────────────────────────────────
log_step(1, "Ingest raw occurrence data")
tryCatch({
  raw <- read_csv(input_file, show_col_types = FALSE) |>
    clean_names()
  log_info("Raw records loaded: %d | Columns: %d", nrow(raw), ncol(raw))
}, error = function(e) {
  log_error(
    "Failed to read input CSV: %s\nProbable cause: corrupted file or not a valid CSV.\nCheck: %s\nPrevious skill: ecological-data-foundation",
    conditionMessage(e), input_file
  )
  stop(e)
})

if (nrow(raw) == 0) {
  log_warn("Input file contains no records: %s", input_file)
}

# ── 2. Require minimum columns ─────────────────────────────────────────────
log_step(2, "Check required columns")
tryCatch({
  required_cols <- c("decimal_latitude", "decimal_longitude", "species")
  missing_req <- setdiff(required_cols, names(raw))
  if (length(missing_req) > 0) {
    log_error(
      "Required columns missing: %s\nProbable cause: CSV gerado por fonte diferente ou com nomes de colunas alterados.\nCheck o schema do arquivo: %s\nPrevious skill: ecological-data-foundation",
      paste(missing_req, collapse = ", "), input_file
    )
    stop("Missing required columns: ", paste(missing_req, collapse = ", "))
  }
  log_info("All required columns present: %s", paste(required_cols, collapse = ", "))
}, error = function(e) {
  log_error("Failed in column validation: %s", conditionMessage(e))
  stop(e)
})

# ── 3. Remove records with missing coordinates ─────────────────────────────
log_step(3, "Remove records without coordinates and convert to numeric")
tryCatch({
  n_before_na <- nrow(raw)
  raw <- raw |>
    filter(!is.na(decimal_latitude), !is.na(decimal_longitude)) |>
    mutate(
      decimal_latitude  = as.numeric(decimal_latitude),
      decimal_longitude = as.numeric(decimal_longitude)
    )
  n_removed_na <- n_before_na - nrow(raw)
  if (n_removed_na > 0) {
    log_warn("Records removed due to missing coordinates: %d", n_removed_na)
  } else {
    log_info("No records removed for missing coordinates.")
  }
}, error = function(e) {
  log_error(
    "Failed to filtrar coordenadas missing: %s\nProbable cause: tipos de coluna inesperados no CSV.\nCheck: %s\nPrevious skill: ecological-data-foundation",
    conditionMessage(e), input_file
  )
  stop(e)
})

if (nrow(raw) < 30) {
  log_warn("Few records after NA removal (%d). Minimum recommended for SDM: 30.", nrow(raw))
}

# ── 4. Coordinate cleaning ─────────────────────────────────────────────────
log_step(4, "Coordinate cleaning with CoordinateCleaner")
log_decision(
  "cc_tests",
  "capitals,centroids,equal,gbif,institutions,validity,zeros",
  "conjunto padrao de testes para detectar registros suspeitos"
)
tryCatch({
  flags <- clean_coordinates(
    x       = raw,
    lon     = "decimal_longitude",
    lat     = "decimal_latitude",
    species = "species",
    tests   = c("capitals", "centroids", "equal", "gbif",
                "institutions", "validity", "zeros"),
    verbose = FALSE
  )

  clean    <- raw[flags$.summary, ] |> mutate(QA_status = "OK")
  flagged  <- raw[!flags$.summary, ] |>
    mutate(QA_status = apply(
      flags[!flags$.summary, grep("^\\.", names(flags))], 1,
      function(r) paste(names(r)[!r], collapse = "|")
    ))

  log_info("Clean records: %d | Flagged records: %d", nrow(clean), nrow(flagged))
  if (nrow(flagged) > 0) {
    log_warn("%d records flagged by CoordinateCleaner (%.1f%% of total).",
             nrow(flagged), 100 * nrow(flagged) / nrow(raw))
  }
}, error = function(e) {
  log_error(
    "Failed in coordinate cleaning (CoordinateCleaner): %s\nProbable cause: malformed data or CoordinateCleaner package not installed.\nCheck: install.packages('CoordinateCleaner')\nPrevious skill: ecological-data-foundation",
    conditionMessage(e)
  )
  stop(e)
})

# ── 5. Remove exact duplicates ─────────────────────────────────────────────
log_step(5, "Remove exact duplicates")
tryCatch({
  n_before <- nrow(clean)
  clean <- clean |> distinct(species, decimal_latitude, decimal_longitude,
                              event_date, .keep_all = TRUE)
  n_dup <- n_before - nrow(clean)
  log_decision(
    "dedup_cols",
    "species,decimal_latitude,decimal_longitude,event_date",
    "combinacao padrao para identificar duplicatas espaciotemporais"
  )
  if (n_dup > 0) {
    log_warn("Duplicatas exatas removidas: %d", n_dup)
  } else {
    log_info("No exact duplicates found.")
  }
}, error = function(e) {
  log_error(
    "Failed to remover duplicatas: %s\nProbable cause: coluna event_date missing ou mal formatada.\nCheck o schema do CSV.\nPrevious skill: ecological-data-foundation",
    conditionMessage(e)
  )
  stop(e)
})

if (nrow(clean) < 30) {
  log_warn(
    "Apenas %d registros limpos apos todas as filtragens. SDMs requerem >= 30 registros confiaveis.",
    nrow(clean)
  )
}

# ── 6. Write outputs ───────────────────────────────────────────────────────
log_step(6, "Write output files")
tryCatch({
  write_csv(clean,   file.path(output_dir, "data_clean.csv"))
  write_csv(flagged, file.path(output_dir, "flagged_records.csv"))
  log_info("Written: %s", file.path(output_dir, "data_clean.csv"))
  log_info("Written: %s", file.path(output_dir, "flagged_records.csv"))
}, error = function(e) {
  log_error(
    "Failed to gravar arquivos de saida: %s\nProbable cause: sem permissao de escrita em '%s'.\nCheck permissoes do directory.\nPrevious skill: ecological-data-foundation",
    conditionMessage(e), output_dir
  )
  stop(e)
})

# ── 7. QA report ──────────────────────────────────────────────────────────
log_step(7, "Generate QA report")
tryCatch({
  report <- c(
    "# QA Report — Occurrence Cleaning",
    "",
    paste("- Input file:", input_file),
    paste("- Raw records:", nrow(raw) + nrow(flagged)),
    paste("- Exact duplicates removed:", n_dup),
    paste("- Records flagged by CoordinateCleaner:", nrow(flagged)),
    paste("- Clean records written:", nrow(clean)),
    "",
    "## Flag Counts",
    ""
  )

  flag_cols <- grep("^\\.", names(flags), value = TRUE)
  for (fc in flag_cols) {
    n_fail <- sum(!flags[[fc]], na.rm = TRUE)
    if (n_fail > 0) report <- c(report, paste0("- `", fc, "`: ", n_fail))
  }

  writeLines(report, file.path(output_dir, "qa_report.md"))
  log_info("Written: %s", file.path(output_dir, "qa_report.md"))
}, error = function(e) {
  log_error(
    "Failed to generate relatorio QA: %s\nProbable cause: problema ao escrever no directory '%s'.\nPrevious skill: ecological-data-foundation",
    conditionMessage(e), output_dir
  )
  stop(e)
})

log_info("Completed. Clean records: %d | Sinalizados: %d", nrow(clean), nrow(flagged))
