#!/usr/bin/env python3
# ecological-agent-skills / Copyright (C) 2026 Francisco Diego Barros Barata
# SPDX-License-Identifier: GPL-3.0-or-later

"""
clean_occurrences.py
Standard occurrence cleaning pipeline using Python.
Usage: python clean_occurrences.py <input_csv> <output_dir> [thin_deg]

Arguments:
    input_csv  : Raw occurrence CSV (output of download_from_gbif.py)
    output_dir : Directory for cleaned output files
    thin_deg   : Grid-cell thinning resolution in decimal degrees (optional).
                 One record is kept per cell. E.g. 0.1 (~11 km), 0.2 (~22 km).
                 Default: no thinning.

Requires: pandas, numpy
"""

import logging
import sys
from datetime import datetime
from pathlib import Path

SKILL_NAME = "ecological-data-foundation"
_LOG_DIR   = Path("logs")
_LOG_DIR.mkdir(parents=True, exist_ok=True)
_log_file  = _LOG_DIR / f"skill_{SKILL_NAME}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] [%(levelname)s] [" + SKILL_NAME + "] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(_log_file, encoding="utf-8"),
    ],
)
logger = logging.getLogger(SKILL_NAME)

def log_step(n: int, desc: str) -> None:
    logger.info("-- STEP %d: %s", n, desc)

def log_decision(var: str, val, why: str) -> None:
    logger.info("DECISION | %s = %s | %s", var, val, why)


import os
import hashlib

import pandas as pd
import numpy as np


def load(path: str) -> pd.DataFrame:
    try:
        df = pd.read_csv(path, low_memory=False)
        logger.info("Loaded %d rows, %d columns from %s", len(df), len(df.columns), path)
        return df
    except FileNotFoundError:
        logger.error(
            "Input not found: %s\n  Probable cause: file not yet generated by the previous step.\n  Check output of: ecological-data-foundation (download_from_gbif)\n  Previous skill: ecological-data-foundation",
            path,
        )
        sys.exit(1)
    except Exception as e:
        logger.error(
            "Failed to read input CSV '%s': %s\n  Probable cause: corrupted file or invalid format.\n  Previous skill: ecological-data-foundation",
            path, e,
        )
        sys.exit(1)


def check_required_cols(df: pd.DataFrame, required: list) -> None:
    missing = [c for c in required if c not in df.columns]
    if missing:
        logger.error(
            "Required columns missing: %s\n  Probable cause: CSV from a different source or schema has changed.\n  Previous skill: ecological-data-foundation",
            missing,
        )
        raise ValueError(f"Missing required columns: {missing}")
    logger.info("All required columns present: %s", required)


def flag_coordinate_issues(df: pd.DataFrame,
                           lat_col="decimalLatitude",
                           lon_col="decimalLongitude") -> pd.DataFrame:
    df = df.copy()
    df["QA_status"] = "OK"
    lat = pd.to_numeric(df[lat_col], errors="coerce")
    lon = pd.to_numeric(df[lon_col], errors="coerce")

    # Invalid range
    mask_range = (lat.abs() > 90) | (lon.abs() > 180)
    df.loc[mask_range, "QA_status"] = "COORD_OUT_OF_RANGE"

    # Zero coordinates
    mask_zero = (lat == 0) & (lon == 0)
    df.loc[mask_zero, "QA_status"] = "COORD_ZERO"

    # Missing coords
    mask_na = lat.isna() | lon.isna()
    df.loc[mask_na, "QA_status"] = "MISSING_COORDS"

    n_range = int(mask_range.sum())
    n_zero  = int(mask_zero.sum())
    n_na    = int(mask_na.sum())

    logger.info(
        "Coordinate issues -- Out of range: %d | Zero: %d | Missing: %d",
        n_range, n_zero, n_na,
    )
    if n_range > 0:
        logger.warning("Records with coordinates outside valid range: %d", n_range)
    if n_zero > 0:
        logger.warning("Records with zero coordinates (0,0): %d — possibly data entry errors", n_zero)
    if n_na > 0:
        logger.warning("Records without coordinates (NA): %d", n_na)
    return df


def remove_exact_duplicates(df: pd.DataFrame,
                             cols=("scientificName","decimalLatitude","decimalLongitude","eventDate")
                             ) -> pd.DataFrame:
    cols_present = [c for c in cols if c in df.columns]
    log_decision(
        "dedup_cols",
        cols_present,
        "standard combination to identify spatiotemporal duplicates",
    )
    n_before = len(df)
    df = df.drop_duplicates(subset=cols_present, keep="first")
    n_removed = n_before - len(df)
    if n_removed > 0:
        logger.warning("Exact duplicates removed: %d", n_removed)
    else:
        logger.info("No exact duplicates found.")
    return df


def check_temporal(df: pd.DataFrame, date_col="eventDate") -> pd.DataFrame:
    if date_col not in df.columns:
        logger.warning("Column '%s' missing -- temporal check skipped.", date_col)
        return df
    dates = pd.to_datetime(df[date_col], errors="coerce")
    future = dates > pd.Timestamp.now()
    n_future = int(future.sum())
    df.loc[future & (df["QA_status"] == "OK"), "QA_status"] = "DATE_FUTURE"
    if n_future > 0:
        logger.warning("Records with future dates flagged: %d", n_future)
    else:
        logger.info("No records with future dates found.")
    return df


def write_outputs(df: pd.DataFrame, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    clean   = df[df["QA_status"] == "OK"]
    flagged = df[df["QA_status"] != "OK"]

    try:
        clean.to_csv(output_dir / "data_clean.csv", index=False)
        logger.info("Written: %s", output_dir / "data_clean.csv")
        flagged.to_csv(output_dir / "flagged_records.csv", index=False)
        logger.info("Written: %s", output_dir / "flagged_records.csv")
    except OSError as e:
        logger.error(
            "Failed to write output files to '%s': %s\n  Probable cause: no write permission in directory.\n  Previous skill: ecological-data-foundation",
            output_dir, e,
        )
        raise

    # QA report
    flag_counts = flagged["QA_status"].value_counts().to_dict()
    lines = [
        "# QA Report — Occurrence Cleaning",
        f"- Raw records: {len(df):,}",
        f"- Clean records: {len(clean):,}",
        f"- Flagged records: {len(flagged):,}",
        "",
        "## Flag Counts",
    ] + [f"- `{k}`: {v}" for k, v in flag_counts.items()]

    try:
        (output_dir / "qa_report.md").write_text("\n".join(lines))
        logger.info("Written: %s", output_dir / "qa_report.md")
    except OSError as e:
        logger.error(
            "Failed to write QA report: %s\n  Probable cause: no write permission.\n  Previous skill: ecological-data-foundation",
            e,
        )
        raise

    if len(clean) < 30:
        logger.warning(
            "Only %d clean records after all filters. SDMs require >= 30 reliable records.",
            len(clean),
        )

    logger.info("Completed. Clean: %d | Flagged: %d", len(clean), len(flagged))
    logger.info("Outputs saved to: %s", output_dir)


def spatial_thin(df: pd.DataFrame, thin_deg: float,
                 lat_col: str = "decimalLatitude",
                 lon_col: str = "decimalLongitude") -> pd.DataFrame:
    """Grid-cell thinning: keep one record per cell of size thin_deg x thin_deg."""
    df = df.copy()
    df["_cell_lon"] = (df[lon_col] / thin_deg).astype(int)
    df["_cell_lat"] = (df[lat_col] / thin_deg).astype(int)
    thinned = df.drop_duplicates(subset=["_cell_lon", "_cell_lat"])
    thinned = thinned.drop(columns=["_cell_lon", "_cell_lat"])
    return thinned


def main():
    logger.info("Script: clean_occurrences.py | Skill: %s", SKILL_NAME)

    input_file = sys.argv[1] if len(sys.argv) > 1 else "data/raw/occurrences.csv"
    output_dir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("data/processed")
    thin_deg   = float(sys.argv[3]) if len(sys.argv) > 3 else None

    logger.info("Input file : %s", input_file)
    logger.info("Output dir : %s", output_dir)
    logger.info("Thin deg   : %s", thin_deg or "disabled")

    # Input precondition check
    if not Path(input_file).exists():
        logger.error(
            "Input not found: %s\n  Probable cause: file not yet generated by the previous step.\n  Check output of: ecological-data-foundation (download_from_gbif)\n  Previous skill: ecological-data-foundation",
            input_file,
        )
        sys.exit(1)

    log_decision("input_file", input_file, "path provided as argv[1] or default")
    log_decision("output_dir", str(output_dir), "path provided as argv[2] or default")
    if thin_deg:
        log_decision(
            "thin_deg", thin_deg,
            "grid-cell spatial thinning — keeps one record per cell; reduces spatial autocorrelation bias in SDMs",
        )

    log_step(1, "Load raw occurrence data")
    df = load(input_file)

    if len(df) == 0:
        logger.warning("Input file contains no records: %s", input_file)

    log_step(2, "Check required columns")
    try:
        check_required_cols(df, ["decimalLatitude", "decimalLongitude"])
    except ValueError as e:
        logger.error("Column verification failed: %s", e)
        sys.exit(1)

    log_step(3, "Flag coordinate issues")
    log_decision(
        "cc_tests",
        "out_of_range,zero,missing",
        "basic coordinate quality checks with no external dependencies",
    )
    try:
        df = flag_coordinate_issues(df)
    except Exception as e:
        logger.error(
            "Failure flagging coordinates: %s\n  Probable cause: coordinate columns have unexpected types.\n  Previous skill: ecological-data-foundation",
            e,
        )
        raise

    log_step(4, "Remove exact duplicates")
    try:
        df = remove_exact_duplicates(df)
    except Exception as e:
        logger.error(
            "Failed to remove duplicates: %s\n  Probable cause: deduplication columns missing or wrong type.\n  Previous skill: ecological-data-foundation",
            e,
        )
        raise

    log_step(5, "Check future dates")
    try:
        df = check_temporal(df)
    except Exception as e:
        logger.error(
            "Failure in temporal check: %s\n  Probable cause: eventDate column has unexpected format.\n  Previous skill: ecological-data-foundation",
            e,
        )
        raise

    if thin_deg:
        log_step(6, f"Spatial thinning ({thin_deg} deg grid cells)")
        n_before = int((df["QA_status"] == "OK").sum())
        try:
            clean_part  = df[df["QA_status"] == "OK"].copy()
            flagged_part = df[df["QA_status"] != "OK"].copy()
            clean_part = spatial_thin(clean_part, thin_deg)
            df = pd.concat([clean_part, flagged_part], ignore_index=True)
            n_after = int((df["QA_status"] == "OK").sum())
            logger.info(
                "Spatial thinning (%g deg): %d -> %d clean records (%d removed)",
                thin_deg, n_before, n_after, n_before - n_after,
            )
        except Exception as e:
            logger.error(
                "Spatial thinning failed: %s\n  Skipping thinning step.\n  Previous skill: ecological-data-foundation",
                e,
            )

    log_step(7, "Write output files and QA report")
    write_outputs(df, output_dir)


if __name__ == "__main__":
    main()
