#!/usr/bin/env python3
# ecological-agent-skills / Copyright (C) 2026 Francisco Diego Barros Barata
# SPDX-License-Identifier: GPL-3.0-or-later
#
# translate_logs.py -- One-shot translation of Portuguese log messages to English
# Usage: python setup/translate_logs.py
# Run from the repository root.

from pathlib import Path

TRANSLATIONS = [
    # Structured error fields (most specific first)
    ("Causa provavel:", "Probable cause:"),
    ("Causa provavel", "Probable cause"),
    ("Colunas obrigatorias ausentes no CSV de metadados", "Required columns missing in metadata CSV"),
    ("Colunas obrigatorias ausentes", "Required columns missing"),
    ("Colunas obrigatorias", "Required columns"),
    ("Skill anterior:", "Previous skill:"),
    ("Skill anterior", "Previous skill"),
    # Verify/Check
    ("Verificar:", "Check:"),
    ("Verificar", "Check"),
    ("Verifique:", "Check:"),
    ("Verifique", "Check"),
    # Not found
    ("nao encontrado", "not found"),
    ("Nao encontrado", "Not found"),
    # Audio / acoustic
    ("Computacao de indices acusticos concluida", "Acoustic index computation completed"),
    ("Deteccao em lote concluida", "Batch detection completed"),
    ("Descobrindo arquivos de audio no diretorio", "Discovering audio files in directory"),
    ("Descobrindo arquivos de audio", "Discovering audio files"),
    ("extensoes em maiusculas nao reconhecidas", "uppercase extensions not recognised"),
    ("extensoes nao reconhecidas", "unrecognised extensions"),
    ("extensoes nao suportadas", "unsupported extensions"),
    ("processado com sucesso", "processed successfully"),
    ("intervalo de frequencia invalido", "invalid frequency range"),
    ("formato de audio incompativel", "incompatible audio format"),
    ("instalacao do BirdNET", "BirdNET installation"),
    ("instalado ou nao esta no PATH", "installed or not in PATH"),
    ("nao instalado", "not installed"),
    # No files / records
    ("Nenhum arquivo de audio encontrado", "No audio files found"),
    ("Nenhum arquivo encontrado", "No files found"),
    ("Nenhum arquivo", "No files"),
    ("Nenhum registro encontrado", "No records found"),
    ("Nenhum registro removido por coordenadas ausentes.", "No records removed for missing coordinates."),
    ("Nenhum registro removido", "No records removed"),
    ("Nenhum registro", "No records"),
    ("Nenhuma deteccao produzida", "No detections produced"),
    ("Nenhuma deteccao", "No detections"),
    ("Nenhum modelo ajustado com sucesso", "No model successfully fitted"),
    # Failure
    ("Falha ao gerar grafico de atividade", "Failed to generate activity plot"),
    ("Falha ao gerar grafico", "Failed to generate plot"),
    ("Falha ao gerar", "Failed to generate"),
    ("Falha ao ler record_table CSV", "Failed to read record_table CSV"),
    ("Falha ao ler metadata CSV", "Failed to read metadata CSV"),
    ("Falha ao ler", "Failed to read"),
    ("Falha ao carregar record_table CSV", "Failed to load record_table CSV"),
    ("Falha ao carregar", "Failed to load"),
    ("Falha em fit_and_check", "Failed in fit_and_check"),
    ("Falha em cameraOperation()", "Failed in cameraOperation()"),
    ("Falha em recordTable()", "Failed in recordTable()"),
    ("Falha em MESS computation", "Failed in MESS computation"),
    ("Falha em", "Failed in"),
    ("Falha ao", "Failed to"),
    # Status / completion
    ("Concluida. Saidas gravadas em", "Completed. Outputs saved to"),
    ("Concluido. Saidas gravadas em", "Completed. Outputs saved to"),
    ("Saidas gravadas em", "Outputs saved to"),
    ("Concluida", "Completed"),
    ("Concluido", "Completed"),
    ("concluida", "completed"),
    ("concluido", "completed"),
    ("Salvo", "Saved"),
    # Data operations
    ("Registros brutos lidos", "Raw records loaded"),
    ("Registros limpos", "Clean records"),
    ("Registros sinalizados", "Flagged records"),
    ("Registros brutos", "Raw records"),
    ("sinalizados", "flagged"),
    ("Remover registros sem coordenadas e converter para numerico",
     "Remove records without coordinates and convert to numeric"),
    ("Remover registros", "Remove records"),
    ("Remover duplicatas exatas", "Remove exact duplicates"),
    ("Remover duplicatas", "Remove duplicates"),
    ("Limpeza de coordenadas com CoordinateCleaner", "Coordinate cleaning with CoordinateCleaner"),
    ("Limpeza de coordenadas", "Coordinate cleaning"),
    ("Limpeza", "Cleaning"),
    # Paths / directories
    ("caminho incorreto ou diretorio nao montado", "incorrect path or directory not mounted"),
    ("caminho incorreto ou arquivo nao gerado ainda", "incorrect path or file not yet generated"),
    ("caminho incorreto", "incorrect path"),
    ("caminho passado como", "path provided as"),
    ("caminho errado", "incorrect path"),
    ("diretorio vazio ou extensoes nao suportadas", "empty directory or unsupported extensions"),
    ("diretorio vazio ou extensoes nao reconhecidas", "empty directory or unrecognised extensions"),
    ("diretorio vazio", "empty directory"),
    ("diretorio de audio existe", "audio directory exists"),
    ("diretorio de audio", "audio directory"),
    ("diretorio de saida", "output directory"),
    ("diretorio de imagens existe e tem permissao de leitura",
     "image directory exists and has read permission"),
    ("diretorio de imagens", "image directory"),
    ("diretorio de trabalho", "working directory"),
    ("diretorio", "directory"),
    # Column / data issues
    ("colunas obrigatorias ausentes", "required columns missing"),
    ("colunas obrigatorias", "required columns"),
    ("colunas ausentes", "missing columns"),
    ("ausentes", "missing"),
    ("ausente", "missing"),
    ("formato de planilha incorreto", "incorrect spreadsheet format"),
    ("formato errado", "incorrect format"),
    ("formato invalido", "invalid format"),
    ("arquivo corrompido ou formato invalido", "corrupted file or invalid format"),
    ("arquivo corrompido ou formato incorreto", "corrupted file or incorrect format"),
    ("arquivo corrompido", "corrupted file"),
    ("arquivo malformado", "malformed file"),
    ("arquivo nao gerado ou nome incorreto", "file not generated or incorrect name"),
    ("arquivo nao gerado ainda", "file not yet generated"),
    ("arquivo nao gerado", "file not yet generated"),
    ("Arquivo de entrada", "Input file"),
    ("arquivo de entrada", "input file"),
    ("arquivo CSV malformado", "malformed CSV file"),
    ("arquivo CSV", "CSV file"),
    ("permissoes insuficientes", "insufficient permissions"),
    # Model / stats
    ("convergencia ou dados insuficientes para a familia escolhida",
     "convergence or insufficient data for the chosen family"),
    ("convergencia", "convergence"),
    ("dados insuficientes", "insufficient data"),
    ("familia escolhida", "chosen family"),
    ("familia de distribuicao", "distribution family"),
    ("formula invalida, colunas ausentes, ou familia incompativel",
     "invalid formula, missing columns, or incompatible family"),
    ("formula invalida", "invalid formula"),
    ("preditores com NA em todas as linhas", "predictors with NA in all rows"),
    ("nome da variavel resposta incorreto", "incorrect response variable name"),
    ("etapa de fitting para mensagens de erro anteriores",
     "fitting step for previous error messages"),
    ("objeto de modelo invalido ou diretorio sem permissao de escrita",
     "invalid model object or directory without write permission"),
    ("diretorio sem permissao de escrita", "directory without write permission"),
    ("objeto de modelo invalido", "invalid model object"),
    # Camera trap
    ("especie rara ou limiar de independencia muito alto",
     "rare species or independence threshold too high"),
    ("especie rara", "rare species"),
    ("limiar de independencia muito alto", "independence threshold too high"),
    ("limiar de independencia", "independence threshold"),
    ("datas em formato errado ou estacoes duplicadas",
     "dates in incorrect format or duplicate stations"),
    ("datas em formato errado", "dates in incorrect format"),
    ("estacoes duplicadas", "duplicate stations"),
    ("estrutura de diretorios incorreta", "incorrect directory structure"),
    ("imagens seguem <Estacao>/<Especie>/<imagens>",
     "images follow <Station>/<Species>/<images>"),
    ("nome de especie incorreto", "incorrect species name"),
    # Misc
    ("Variavel nao definida", "Variable not defined"),
    ("Coluna nao encontrada", "Column not found"),
    ("Observacoes", "Observations"),
    ("Reprojeccao", "Reprojection"),
    ("Preparacao", "Preparation"),
    ("Construcao da superficie de resistencia", "Resistance surface construction"),
    ("Construcao", "Construction"),
    ("Minimo de nos para analise de grafo", "Minimum nodes for graph analysis"),
    ("Minimo", "Minimum"),
    ("instalacao do pacote overlap", "overlap package installation"),
    ("biblioteca overlap com problema", "overlap library issue"),
    # Annotation tags
    ("[nenhuma — etapa inicial]", "[none — initial step]"),
    ("[nenhuma — dependencia externa]", "[none — external dependency]"),
    ("[nenhuma]", "[none]"),
    # Sixth-pass: final residuals
    ("Pulando.", "Skipping."),
    ("nenhuma quebra estrutural detectada.", "no structural breakpoint detected."),
    ("Nenhum argumento fornecido. Usando valores padrao.",
     "No arguments provided. Using default values."),
    ("Resolucao %g nao e um valor padrao do WorldClim (0.5, 2.5, 5, 10). Pode causar erro no download.",
     "Resolution %g is not a standard WorldClim value (0.5, 2.5, 5, 10). May cause download error."),
    ("Resolucao %g nao e padrao WorldClim. Valores validos: 0.5, 2.5, 5, 10.",
     "Resolution %g is not a standard WorldClim value. Valid values: 0.5, 2.5, 5, 10."),
    ("MODIS: download requer conta NASA EarthData (nao automatizado)",
     "MODIS: download requires NASA EarthData account (not automated)"),
    ("Nenhuma camada baixada com sucesso. Arquivo de metadata nao criado.",
     "No layers downloaded successfully. Metadata file not created."),
    ("Stack mascarado nao contem celulas validas",
     "Masked stack contains no valid cells"),
    ("a study area pode nao sobrepor os rasters.",
     "the study area may not overlap the rasters."),
    ("arquivo shapefile/GeoPackage nao existe ou incorrect path",
     "shapefile/GeoPackage file does not exist or incorrect path"),
    ("se o a", "that the"),  # partial fix for truncated message
    ("Carregando camada de manchas de habitat", "Loading habitat patch layer"),
    ("Coluna '%s' nao encontrada; calculando area a partir da geometria",
     "Column '%s' not found; computing area from geometry"),
    ("Calculando distancias entre centroides das manchas",
     "Computing distances between patch centroids"),
    ("Construindo grafo de adjacencia binaria", "Building binary adjacency graph"),
    ("Nenhuma mancha conectada dentro de dmax = %g m; aumente dmax_m ou verifique CRS",
     "No patches connected within dmax = %g m; increase dmax_m or check CRS"),
    ("Calculando IIC", "Computing IIC"),
    ("Calculando dIIC por mancha (leave-one-out)", "Computing dIIC per patch (leave-one-out)"),
    ("Calculando dIIC para cada mancha (pode levar um momento)...",
     "Computing dIIC for each patch (may take a moment)..."),
    ("Calculando PC", "Computing PC"),
    ("Calculando dPC por mancha (leave-one-out)", "Computing dPC per patch (leave-one-out)"),
    ("Calculando dPC para cada mancha...", "Computing dPC for each patch..."),
    ("Escrevendo resumo da paisagem e metricas por mancha",
     "Writing landscape summary and per-patch metrics"),
    ("Gerando visualizacao do grafo de conectividade",
     "Generating connectivity graph visualisation"),
    ("Nao foi possivel salvar visualizacao do grafo:",
     "Could not save graph visualisation:"),
    ("CSV de resistencia nao existe", "resistance CSV does not exist"),
    ("se o arquivo contem colunas lc_cod", "that the file contains lc_cod columns"),
    ("Calculando estatisticas da superficie de resistencia",
     "Computing resistance surface statistics"),
    ("Gerando visualizacao do mapa de resistencia",
     "Generating resistance map visualisation"),
    ("Nao foi possivel gerar mapa de resistencia:",
     "Could not generate resistance map:"),
    ("passo anterior nao concluiu.", "previous step did not complete."),
    ("outputs do skill anterior.", "outputs of the previous skill."),
    ("Nenhuma coluna de elemento de matriz encontrada.", "No matrix element columns found."),
    ("CSV nao tem colunas no padrao a_i_j.", "CSV has no columns in the a_i_j pattern."),
    ("serie temporal muito curta ou valores NA excessivos.",
     "time series too short or excessive NA values."),
    ("numero d", "number o"),
    ("Nenhuma coluna de elemento de matriz (a_i_j) encontrada no CSV.",
     "No matrix element columns (a_i_j) found in CSV."),
    ("incorrect format do arquivo", "incorrect file format"),
    ("colunas nao numericas ou valores NA remanescentes.",
     "non-numeric columns or remaining NA values."),
    ("Diretorio de features not found:", "Features directory not found:"),
    ("passo anterior nao concluiu ou incorrect path.",
     "previous step did not complete or incorrect path."),
    ("outputs do skill anterior ou incorrect path.",
     "previous skill outputs or incorrect path."),
    ("No files .tif encontrado em:", "No .tif files found in:"),
    ("features_dir incorreto ou features nao geradas.",
     "incorrect features_dir or features not generated."),
    ("conteudo do", "contents of"),
    ("Nenhuma feature valida apos remocao de zero-sum.",
     "No valid features after zero-sum removal."),
    ("todas as features tem distribuicao zero na",
     "all features have zero distribution in"),
    ("Cenario BLM=%g nao produziu solucao.", "BLM=%g scenario produced no solution."),
    ("Cenario de alvo %.2fx nao produziu solucao.",
     "Target %.2fx scenario produced no solution."),
    ("Cenario de custo '%s' nao produziu solucao.",
     "Cost '%s' scenario produced no solution."),
    ("features nao geradas ou incorrect path.", "features not generated or incorrect path."),
    ("features nao sobrep", "features do not overlap"),
    ("%d features com soma zero excluidas (nenhuma ocorrencia na study area):",
     "%d zero-sum features excluded (no occurrences in study area):"),
    ("Nenhuma feature valida apos remocao de zero-sum.\nProbable cause: features nao sobrep",
     "No valid features after zero-sum removal.\nProbable cause: features do not overlap"),
    ("Raster locked-in fornecido mas nenhuma PU com valor 1 encontrada.",
     "Locked-in raster provided but no PU with value 1 found."),
    ("Raster locked-out fornecido mas nenhuma PU com valor 1 encontrada.",
     "Locked-out raster provided but no PU with value 1 found."),
    ("Nenhuma PU selecionada na solucao. Check viabilidade do problema e restricoes locked-out.",
     "No PUs selected in solution. Check problem feasibility and locked-out constraints."),
    ("%d features nao atingiram seus alvos de representacao. Check viabilidade e restricoes.",
     "%d features did not meet their representation targets. Check feasibility and constraints."),
    ("Nao foi possivel gerar o mapa de priorizacao: %s. Continuando sem o grafico.",
     "Could not generate prioritisation map: %s. Continuing without plot."),
    ("run_ensemble_sdm.R nao foi executado.", "run_ensemble_sdm.R was not executed."),
    ("a saida de skills/spec", "the output of skills/spec"),
    ("stack nao foi preparado.", "stack was not prepared."),
    ("Falha na predicao generica:", "Failed in generic prediction:"),
    ("model class nao suportada.", "model class not supported."),
    ("model_obj e um dos tipos s", "model_obj is one of the supported types"),
    ("Recorte e mascara aplicados. Celulas validas apos mascara: nao calculado",
     "Clip and mask applied. Valid cells after mask: not calculated"),
    ("use global(future_masked, 'notNA'))", "use global(future_masked, 'notNA'))"),
    ("run_ensemble_sdm.R nao concluiu.", "run_ensemble_sdm.R did not complete."),
    ("prepare_future_layers.R nao foi executado.", "prepare_future_layers.R was not executed."),
    ("Nenhum .tif encontrado em:", "No .tif files found in:"),
    ("prepare_future_layers.R nao gerou os stacks.", "prepare_future_layers.R did not generate the stacks."),
    ("Construindo background a partir de valores env no CSV. Para uso em producao, use um SpatRaster real.",
     "Building background from env values in CSV. For production use, provide a real SpatRaster."),
    ("Coluna 'type' missing. Gerando pseudo-background por jitter. Use um CSV de background real em producao.",
     "Column 'type' missing. Generating pseudo-background by jitter. Use a real background CSV in production."),
    ("Nao foi possivel analisar", "Could not analyse"),
    ("Limiar de confianca:", "Confidence threshold:"),
    ("Timestamp nao extraido do nome do arquivo:", "Timestamp not extracted from file name:"),
    ("Escrevendo deteccoes brutas e filtradas", "Writing raw and filtered detections"),
    ("Construindo lista de especies detectadas", "Building detected species list"),
    ("Gerando resumo de deteccoes por hora", "Generating detection summary by hour"),
    ("Calculando acumulacao de especies", "Computing species accumulation"),
    ("Nao foi possivel carregar", "Could not load"),
    ("Escrevendo CSV de serie temporal", "Writing time series CSV"),
    ("Escrevendo resumo por hora do dia", "Writing summary by hour of day"),
    ("Carregando registros da tabela CSV", "Loading records from CSV table"),
    ("Calculando resumo por especie e estacao",
     "Computing summary by species and station"),
    ("station_summary.csv: %d estacoes", "station_summary.csv: %d stations"),
    ("Gerando grafico de linha do tempo de deteccoes",
     "Generating detection timeline plot"),
    ("Nenhum taxon key GBIF encontrado para", "No GBIF taxon key found for"),
    ("occ.search nao gera DOI. Para publicacoes, use download assincrono.",
     "occ.search does not generate a DOI. For publications, use async download."),
    ("Gravar metadados do download", "Save download metadata"),
    ("Gravar metadados", "Save metadata"),
    # Fifth-pass: remaining scattered strings
    ("Sobreposicao Dhat4 =", "Dhat4 overlap ="),
    ("Escrevendo arquivos de saida", "Writing output files"),
    ("  record_table.csv: %d eventos independentes",
     "  record_table.csv: %d independent events"),
    ("  trap_effort_summary.csv: %d estacoes",
     "  trap_effort_summary.csv: %d stations"),
    ("Input file nao contem registros:", "Input file contains no records:"),
    ("Nenhuma duplicata exata encontrada.", "No exact duplicates found."),
    ('"nenhum"', '"none"'),
    ("nenhum (global)", "none (global)"),
    ("argumento nao e CSV file existente", "argument is not an existing CSV file"),
    ("argumento nao e CSV file", "argument is not a CSV file"),
    ("argumento nao e um CSV file existente", "argument is not an existing CSV file"),
    ("No records para '%s'. Pulando.", "No records for '%s'. Skipping."),
    ("Taxon key GBIF not found para", "GBIF taxon key not found for"),
    ("occ_search nao gera DOI. Para publicacoes, use occ_download.",
     "occ_search does not generate a DOI. For publications, use occ_download."),
    ("Metadados gravados:", "Metadata saved:"),
    ("Nenhum resultado IUCN para '%s'. Especie pode nao estar avaliada.",
     "No IUCN results for '%s'. Species may not have been assessed."),
    ("Failed to gravar metadados para", "Failed to save metadata for"),
    ("Apenas %d site(s) detectado(s)",
     "Only %d site(s) detected"),
    ("efeitos aleatorios podem nao ser estimaveis.",
     "random effects may not be estimable."),
    ("Menos de 2 indicadores de ES encontrados",
     "Fewer than 2 ES indicators found"),
    ("analise de trade-off nao e possivel com apenas %d coluna(s).",
     "trade-off analysis not possible with only %d column(s)."),
    ("Gerando %d graficos de dispersao (de %d pares possiveis)",
     "Generating %d scatter plots (of %d possible pairs)"),
    ("Carregar e parsear serie temporal", "Load and parse time series"),
    ("Carregar serie temporal e validar coluna 'value'",
     "Load time series and validate 'value' column"),
    ("Minimum pos-disturbio", "Minimum post-disturbance"),
    ("nao e menor que a media baseline",
     "is not lower than the baseline mean"),
    ("possivel ausencia de disturbio detectavel.",
     "possible absence of detectable disturbance."),
    ("Apenas %d obs com RI > 0.01",
     "Only %d obs with RI > 0.01"),
    ("modelo exponencial nao ajustado (minimo 5 necessario).",
     "exponential model not fitted (minimum 5 required)."),
    ("Gerar grafico de contexto da serie temporal completa",
     "Generate full time series context plot"),
    ("Nenhuma tendencia significativa detectada",
     "No significant trend detected"),
    # Fourth-pass: log_step descriptions and log_info/log_warn bodies
    # acoustic-monitoring
    ("Computando indices acusticos por arquivo", "Computing acoustic indices per file"),
    ("Computando indices — pode levar varios minutos para grandes conjuntos de dados...",
     "Computing indices — may take several minutes for large datasets..."),
    ("Computando indices - pode levar varios minutos para grandes conjuntos de dados...",
     "Computing indices — may take several minutes for large datasets..."),
    ("Pulando %s:", "Skipping %s:"),
    ("Pulando heatmap: nenhum timestamp disponivel nos arquivos de audio",
     "Skipping heatmap: no timestamps available in audio files"),
    ("%d de %d arquivos processados com sucesso", "%d of %d files processed successfully"),
    ("Nenhum timestamp extraido dos nomes de arquivo. Heatmap nao sera gerado.",
     "No timestamps extracted from file names. Heatmap will not be generated."),
    ("Agregando indices por resolucao temporal", "Aggregating indices by temporal resolution"),
    ("Escrevendo CSV de serie temporal de indices", "Writing index time series CSV"),
    ("Calculando e escrevendo resumo por hora do dia", "Computing and writing summary by hour of day"),
    ("Gerando heatmap de paisagem sonora", "Generating soundscape heatmap"),
    # camera-trap
    ("Grafico de atividade salvo: activity_plot.png", "Activity plot saved: activity_plot.png"),
    ("Calculando estatisticas circulares", "Computing circular statistics"),
    ("mle.vonmises() falhou (kappa = NA):", "mle.vonmises() failed (kappa = NA):"),
    ("Rayleigh p = %.4f >= 0.05: atividade diaria nao difere de uniforme para",
     "Rayleigh p = %.4f >= 0.05: daily activity does not differ from uniform for"),
    ("Calculando sobreposicao de atividade entre grupos (se aplicavel)",
     "Computing activity overlap between groups (if applicable)"),
    ("Estimando sobreposicao Dhat4 entre", "Estimating Dhat4 overlap between"),
    ("Um ou ambos os grupos tem < 10 eventos; sobreposicao nao calculada",
     "One or both groups have < 10 events; overlap not calculated"),
    ("group_col '%s' tem %d valores unicos; exatamente 2 necessarios para sobreposicao",
     "group_col '%s' has %d unique values; exactly 2 required for overlap"),
    ("Coluna de grupo '%s' nao encontrada nos dados da especie",
     "Group column '%s' not found in species data"),
    ("Hora media de atividade:", "Mean activity hour:"),
    ("Carregando metadados das cameras", "Loading camera metadata"),
    ("Metadados carregados: %d estacoes", "Metadata loaded: %d stations"),
    ("Construindo matriz de operacao das cameras", "Building camera operation matrix"),
    ("datas em incorrect format ou duplicate stations",
     "dates in incorrect format or duplicate stations"),
    ("Estacoes com < 100 armadilhas-noite (insufficient data para ocupancia):",
     "Stations with < 100 trap-nights (insufficient data for occupancy):"),
    ("Construindo tabela de registros a partir das imagens",
     "Building record table from images"),
    ("Limiar de independencia: %d min", "Independence threshold: %d min"),
    ("estrutura de directorys incorreta", "incorrect directory structure"),
    ("se images fo", "that images fo"),
    ("Tabela de registros construida: %d eventos independentes",
     "Record table built: %d independent events"),
    ("Calculando resumo de registros por especie",
     "Computing record summary per species"),
    ("Especies com < 10 eventos independentes (apenas RAI; sem ocupancia):",
     "Species with < 10 independent events (RAI only; no occupancy):"),
    ("Gerando historicos de deteccao por especie",
     "Generating detection histories per species"),
    ("detectionHistory() falhou para especie", "detectionHistory() failed for species"),
    ("Check: estrutu", "Check: struct"),
    # Third-pass residuals
    ("Serie temporal curta", "Short time series"),
    ("Estimativas de variancia podem ser imprecisas; n_sim alto recomendado.",
     "Variance estimates may be imprecise; high n_sim recommended."),
    ("Menos de 10 extincoes observadas", "Fewer than 10 extinctions observed"),
    ("Intervalo de confianca do MTE nao calculado.", "MTE confidence interval not calculated."),
    ("Registros com coordenadas validas:", "Records with valid coordinates:"),
    ("Falha na requisicao OBIS", "OBIS request failed"),
    ("sem conexao com a internet ou API OBIS indisponivel.",
     "no internet connection or OBIS API unavailable."),
    ("Falha na requisicao IUCN API", "IUCN API request failed"),
    ("chave invalida ou API indisponivel.", "invalid key or API unavailable."),
    ("Paises de ocorrencia:", "Occurrence countries:"),
    ("Registros no schema padrao:", "Records in standard schema:"),
    ("Diretorio de saida pronto:", "Output directory ready:"),
    ("Total de observacoes recuperadas:", "Total observations retrieved:"),
    ("Filtro de pais aplicado:", "Country filter applied:"),
    ("Status do download:", "Download status:"),
    ("Padronizar e gravar CSVs por especie", "Standardise and write CSVs per species"),
    ("Executar download iNaturalist para todas as especies",
     "Run iNaturalist download for all species"),
    ("Coluna de nome cientifico nao encontrada no chunk %d; pulando.",
     "Scientific name column not found in chunk %d; skipping."),
    ("Total de linhas lidas no EBD:", "Total rows read from EBD:"),
    ("Total de registros filtrados do EBD:", "Total records filtered from EBD:"),
    ("Falha na verificacao de colunas:", "Failed in column validation:"),
    ("Falha na limpeza de coordenadas (CoordinateCleaner)",
     "Failed in coordinate cleaning (CoordinateCleaner)"),
    ("dados malformados ou pacote CoordinateCleaner not installed.",
     "malformed data or CoordinateCleaner package not installed."),
    ("Numero de linhas baixo", "Low row count"),
    ("Estimativas de correlacao podem ser instáveis com n < 30.",
     "Correlation estimates may be unstable with n < 30."),
    ("Apenas %d variavel encontrada. Analise de colinearidade requer pelo menos 2 preditores.",
     "Only %d variable found. Collinearity analysis requires at least 2 predictors."),
    ("CSV incorreto ou sem preditores numericos.", "Incorrect CSV or no numeric predictors."),
    ("formato do arquivo env_matrix_csv.", "env_matrix_csv file format."),
    ("Resumo da paisagem gravado:", "Landscape summary saved:"),
    ("Metricas por mancha gravadas:", "Per-patch metrics saved:"),
    ("manchas)", "patches)"),
    ("Visualizacao do grafo salva:", "Graph visualisation saved:"),
    ("Analise de conectividade completed", "Connectivity analysis completed"),
    # Residual mixed fragments (partial translations missed in first pass)
    ("raster de projecao not found", "projection raster not found"),
    ("arquivo GeoTIFF corrompido ou formato nao suportado pelo terra.",
     "corrupted GeoTIFF file or format not supported by terra."),
    ("arquivo GeoTIFF corrompido ou formato nao suportado",
     "corrupted GeoTIFF file or format not supported"),
    ("arquivo GeoTIFF nao gerado", "GeoTIFF file not generated"),
    ("nomes de camadas divergem entre stacks de treinamento e projecao.",
     "layer names differ between training and projection stacks."),
    ("Camadas missing na projecao:", "Layers missing in projection:"),
    ("stacks gerados com variaveis diferentes", "stacks generated with different variables"),
    ("que ambos os TIFs tem as mesmas bandas nomeadas",
     "that both TIFs have the same named bands"),
    ("raster de treinamento com todos os pixels NA",
     "training raster with all NA pixels"),
    ("mascara e extent do raster de treinamento",
     "training raster mask and extent"),
    ("memoria insuficiente para rasters grandes ou valores NA inesperados",
     "insufficient memory for large rasters or unexpected NA values"),
    ("tamanho do raster de projecao e memoria disponivel",
     "projection raster size and available memory"),
    ("rasters MOP ou MESS invalidos", "invalid MOP or MESS rasters"),
    ("etapas anteriores para mensagens de erro",
     "previous steps for error messages"),
    ("dispositivo grafico nao disponivel ou rasters invalidos",
     "graphics device not available or invalid rasters"),
    ("disponibilidade de X11/display e integridade dos rasters",
     "X11/display availability and raster integrity"),
    ("integridade dos arquivos TIF com gdalinfo",
     "TIF file integrity using gdalinfo"),
    ("integridade do raster", "raster integrity"),
    ("stack de calibracao", "calibration stack"),
    ("area de estudo", "study area"),
    ("shapefile corrompido, projecao invalida ou formato nao suportado.",
     "corrupted shapefile, invalid projection or unsupported format."),
    ("gravar raster de saida", "write output raster"),
    ("sem permissao de escrita ou espaco em disco insuficiente.",
     "no write permission or insufficient disk space."),
    ("falha do solver HiGHS ou dados raster invalidos.",
     "HiGHS solver failure or invalid raster data."),
    ("instalacao do HiGHS e integridade dos rasters.",
     "HiGHS installation and raster integrity."),
    ("falha do solver ou raster de custo invalido.",
     "solver failure or invalid cost raster."),
    ("valores do raster pu e instalacao do HiGHS.",
     "pu raster values and HiGHS installation."),
    ("Dados insuficientes para grafico BLM (menos de 3 pontos). Grafico nao gerado.",
     "Insufficient data for BLM plot (fewer than 3 points). Plot not generated."),
    ("CSV de pontos nao gerado ou incorrect path.",
     "points CSV not generated or incorrect path."),
    ("execute primeiro o script de limpeza de ocorrencias.",
     "run the occurrence cleaning script first."),
    ("reprojetar pontos para CRS do stack",
     "reproject points to stack CRS"),
    ("CRS do stack invalido ou nao suportado pela transformacao.",
     "invalid stack CRS or transformation not supported."),
    ("CRS do stack de rasters.", "raster stack CRS."),
    ("nenhuma.", "[none]."),
    ("raster de cobertura de terra nao existe",
     "land cover raster does not exist"),
    ("caminho e existencia do arquivo .tif",
     "file path and existence of .tif"),
    ("[nenhuma — entrada do usuario]", "[none — user input]"),
    ("Carregando raster de cobertura de terra e tabela de resistencia",
     "Loading land cover raster and resistance table"),
    ("load raster de cobertura de terra", "load land cover raster"),
    ("arquivo .tif corrompido ou invalid format",
     "corrupted .tif file or invalid format"),
    ("ou directory nao montado", "or directory not mounted"),
    ("CSV file de metadados nao gerado ou nome incorreto",
     "metadata CSV file not generated or incorrect name"),
    ("se o arquivo existe e o caminho esta correto",
     "that the file exists and path is correct"),
    ("matplotlib nao disponivel; pulando heatmap",
     "matplotlib not available; skipping heatmap"),
    ("Sem timestamps validos; heatmap nao gerado",
     "No valid timestamps; heatmap not generated"),
    ("Sem timestamps horarios disponíveis; detection_summary.csv nao gerado",
     "No hourly timestamps available; detection_summary.csv not generated"),
    ("rasterio nao disponivel; sem corte de extensao.",
     "rasterio not available; no extent clipping."),
    ("Corte de camadas por extensao nao disponivel.",
     "Layer clipping by extent not available."),
    # BioStatistics
    ("cabecalho do CSV e o argumento response_var",
     "CSV header and the response_var argument"),
    ("cabecalho do CSV", "CSV header"),
    ("argumento data_csv e o diretorio de trabalho",
     "data_csv argument and working directory"),
    ("argumento data_csv", "data_csv argument"),
    ("argumento response_var", "response_var argument"),
    ("encoding e estrutura do arquivo CSV", "encoding and structure of the CSV file"),
    ("completude dos dados e formulas dos candidatos",
     "data completeness and candidate formulas"),
    ("formulas dos candidatos", "candidate formulas"),
    # Geoprocessing/SDM
    ("versoes de terra e dismo, e que os rasters tem CRS definido",
     "terra and dismo versions, and that rasters have CRS defined"),
    ("versoes de terra e dismo", "terra and dismo versions"),
    ("rasters tem CRS definido", "rasters have CRS defined"),
    ("incompatibilidade entre pacotes terra/raster ou raster sem CRS",
     "incompatibility between terra/raster packages or raster without CRS"),
    # clean_occurrences specific
    ("sem coordenadas e converter para numerico", "without coordinates and convert to numeric"),
    ("sem coordenadas", "without coordinates"),
    ("limpos:", "clean:"),

    # ── Seventh pass ─────────────────────────────────────────────────────────

    # Common step descriptions
    ("Analisar argumentos da linha de comando", "Parse command-line arguments"),
    ("Construir lista de especies", "Build species list"),
    ("Executar download para todas as especies", "Run download for all species"),
    ("Executar download IUCN para todas as especies", "Run IUCN download for all species"),
    ("Executar download OBIS para todas as especies", "Run OBIS download for all species"),
    ("Definir filtros padrao de download", "Define default download filters"),
    ("Check existencia do arquivo EBD", "Check EBD file existence"),
    ("Filtrar e carregar EBD com auk", "Filter and load EBD with auk"),
    ("Check chave da API IUCN", "Check IUCN API key"),
    ("Carregar tabela de servicos ecossistemicos", "Load ecosystem services table"),
    ("Identificar colunas de indicadores de ES e normalizar 0-1",
     "Identify ES indicator columns and normalise 0-1"),
    ("Calcular matriz de correlacao de Spearman entre indicadores de ES",
     "Compute Spearman correlation matrix among ES indicators"),
    ("Gerar heatmap de trade-offs (corrplot)", "Generate trade-off heatmap (corrplot)"),
    ("Gerar graficos de dispersao para pares de indicadores de ES",
     "Generate scatter plots for ES indicator pairs"),
    ("Calcular estatisticas de baseline pre-disturbio (ultimos 24 meses)",
     "Compute pre-disturbance baseline statistics (last 24 months)"),
    ("Identificar minimo pos-disturbio com suavizacao (janela 3)",
     "Identify post-disturbance minimum with smoothing (window 3)"),
    ("Ajustar curvas de recuperacao (linear e exponencial)",
     "Fit recovery curves (linear and exponential)"),
    ("Estimar tempo para 80%% e 100%% de recuperacao (modelo linear)",
     "Estimate time to 80%% and 100%% recovery (linear model)"),
    ("Gerar grafico de trajetoria de recuperacao", "Generate recovery trajectory plot"),
    ("Analise de recuperacao completed", "Recovery analysis completed"),
    ("Teste de Mann-Kendall e inclinacao de Sen", "Mann-Kendall test and Sen slope"),
    ("Detectar quebras estruturais com BFAST", "Detect structural breaks with BFAST"),
    ("Calcular anomalias em relacao ao baseline", "Compute anomalies relative to baseline"),
    ("Analise de tendencia completed", "Trend analysis completed"),
    ("Reclassificando cobertura de terra para resistencia",
     "Reclassifying land cover to resistance"),
    ("Combinando camadas de resistencia e normalizando",
     "Combining resistance layers and normalising"),
    ("Listar e empilhar rasters .tif do directory de entrada",
     "List and stack .tif rasters from input directory"),
    ("Reprojetar study area e recortar stack de rasters",
     "Reproject study area and crop raster stack"),
    ("Salvar stack de rasters processado", "Save processed raster stack"),
    ("Carregar pontos de ocorrencia e extrair valores ambientais",
     "Load occurrence points and extract environmental values"),
    ("Gravar metadata de preditores", "Write predictor metadata"),
    ("Interpretar extensao WKT para corte de camadas",
     "Parse WKT extent for layer clipping"),
    ("Sem extensao de corte", "No clip extent"),
    ("camadas globais serao salvas integralmente",
     "global layers will be saved in full"),
    ("Ler parametros do arquivo YAML", "Read parameters from YAML file"),
    ("Executar busca em grade ENMeval (MaxNet)", "Run ENMeval grid search (MaxNet)"),
    ("Extrair e processar tabela de resultados da calibracao",
     "Extract and process calibration results table"),
    ("Selecionar melhores modelos pelo criterio OR_AICc",
     "Select best models by OR_AICc criterion"),
    ("Gerar grafico de calibracao (delta_AICc x OR10)",
     "Generate calibration plot (delta_AICc vs OR10)"),
    ("Ajustar modelo final com os melhores parametros",
     "Fit final model with best parameters"),
    ("Exibir resumo da calibracao", "Display calibration summary"),
    ("Carregar dados de ocorrencia com variaveis ambientais",
     "Load occurrence data with environmental variables"),
    ("Preparar dados ambientais e pontos de background",
     "Prepare environmental data and background points"),
    ("Scaffold carregado", "Scaffold loaded"),
    ("Carregar calibration stack de referencia", "Load reference calibration stack"),
    ("Carregar study area (G area)", "Load study area (G area)"),
    ("Carregar camadas climaticas futuras", "Load future climate layers"),
    ("Renomear camadas futuras para coincidir com a calibracao",
     "Rename future layers to match calibration"),
    ("Reprojetar stack futuro para o CRS de calibracao",
     "Reproject future stack to calibration CRS"),
    ("Recortar e mascarar para a study area", "Crop and mask to study area"),
    ("Reamostrar para coincidir exatamente com o grid de calibracao",
     "Resample to match calibration grid exactly"),
    ("Check geometria do stack futuro contra o de calibracao",
     "Check future stack geometry against calibration"),
    ("Check nomes finais das camadas", "Check final layer names"),
    ("Gravar stack futuro preparado", "Write prepared future stack"),
    ("Exibir resumo das camadas futuras preparadas", "Display prepared future layers summary"),
    ("Analise de trade-off completed", "Trade-off analysis completed"),
    ("Analisar arquivo EBD em chunks", "Parse EBD file in chunks"),

    # Specific log messages
    ("Menos de 4 argumentos. Usando caminhos padrao para teste.",
     "Fewer than 4 arguments. Using default paths for testing."),
    ("Menos de 2 argumentos. Usando valores padrao para teste interativo.",
     "Fewer than 2 arguments. Using default values for interactive testing."),
    ("Stack de calibracao : %s", "Calibration stack  : %s"),
    ("Area de estudo      : %s", "Study area         : %s"),
    ("cenario SSP para rotular o arquivo de saida",
     "SSP scenario label for output file naming"),
    ("horizonte temporal para rotular o arquivo de saida",
     "temporal horizon label for output file naming"),
    ("Reprojetando study area para o CRS de calibracao...",
     "Reprojecting study area to calibration CRS..."),
    ("CRS da study area ja coincide com o de calibracao. Sem reprojecao necessaria.",
     "Study area CRS already matches calibration. No reprojection needed."),
    ("Arquivos de camada futura encontrados: %d", "Future layer files found: %d"),
    ("mesmo number oe camadas mas nomes diferentes (comum com CHELSA)",
     "same number of layers but different names (common with CHELSA)"),
    ("Numero de camadas difere. Tentando correspondencia por nome parcial...",
     "Layer count differs. Attempting partial name matching..."),
    ("Reprojetando stack futuro para CRS de calibracao...",
     "Reprojecting future stack to calibration CRS..."),
    ("interpolacao bilinear para dados continuos de clima",
     "bilinear interpolation for continuous climate data"),
    ("CRS ja coincide com calibracao. Sem reprojecao necessaria.",
     "CRS already matches calibration. No reprojection needed."),
    ("compareGeom retornou erro: %s. Prosseguindo com cautela.",
     "compareGeom returned error: %s. Proceeding with caution."),
    ("Verificacao de geometria PASSOU.", "Geometry check PASSED."),
    ("CRS de saida       : %s", "Output CRS         : %s"),
    ("Resolucao de saida : %s unidades", "Output resolution  : %s units"),
    ("Arquivo de saida   : %s", "Output file        : %s"),
    ("Camadas preparadas : %d", "Prepared layers    : %d"),
    ("Nomes das camadas  : %s", "Layer names        : %s"),
    ("Horizonte temporal : %s", "Temporal horizon   : %s"),
    ("========== RESUMO DAS CAMADAS FUTURAS ==========",
     "========== PREPARED FUTURE LAYERS SUMMARY =========="),
    ("=================================================",
     "====================================================="),
    ("Pronto para: maxnet::predict(), biomod2::BIOMOD_Projection() ou sdm_pipeline.py",
     "Ready for: maxnet::predict(), biomod2::BIOMOD_Projection() or sdm_pipeline.py"),
    ("Nomes das camadas coincidentes. Reordenados conforme calibracao.",
     "Layer names match. Reordered to match calibration."),
    ("nomes identicos, apenas reordenados", "identical names, reordered only"),
    ("Nomes antigos: %s", "Old names  : %s"),
    ("Novos nomes  : %s", "New names  : %s"),
    ("Camadas associadas por nome parcial. Reordenadas conforme calibracao.",
     "Layers matched by partial name. Reordered to match calibration."),
    ("contagem diferente; correspondencia por substring",
     "different count; matched by substring"),
    ("Reprojecao completed.", "Reprojection completed."),
    ("Nomes das camadas futuras (brutos): %s", "Raw future layer names: %s"),
    ("Nomes das camadas verificados. Camadas: %s",
     "Layer names verified. Layers: %s"),
    ("Gravado: %s", "Written: %s"),
    ("Falha na predicao ensemble: %s\nProbable cause: modelos incompativeis.\nCheck: todos os modelos foram treinados com os mesmos preditores.",
     "Failed ensemble prediction: %s\nProbable cause: incompatible models.\nCheck: all models were trained with the same predictors."),
    ("Rscript gerou o modelo com saveRDS().", "Rscript generated the model with saveRDS()."),
    ("prepare_future_layers.R did not generate the stacks.\nCheck: arquivos .tif existem em scenarios_dir.",
     "prepare_future_layers.R did not generate the stacks.\nCheck: .tif files exist in scenarios_dir."),
    ("Falha na projecao do cenario %s: %s\nCheck: stack tem os mesmos preditores do modelo.",
     "Failed projecting scenario %s: %s\nCheck: stack has the same predictors as the model."),
    ("semente global definida no params.yaml para reprodutibilidade",
     "global seed defined in params.yaml for reproducibility"),
    ("algoritmos definidos em params.yaml$modeling$algorithms",
     "algorithms defined in params.yaml$modeling$algorithms"),
    ("metodo de validacao cruzada definido em params.yaml",
     "cross-validation method defined in params.yaml"),
    ("number oe folds definido em params.yaml", "number of folds defined in params.yaml"),
    ("preencher com carregamento de dados e chamadas de modelo",
     "fill with data loading and model calls"),
    ("Adicione o carregamento de dados e as chamadas de modelo para seu estudo.",
     "Add data loading and model calls for your study."),
    ("grade de multiplicadores de regularizacao para busca em grade MaxEnt",
     "regularisation multiplier grid for MaxEnt grid search"),
    ("grade de classes de features para busca em grade MaxEnt",
     "feature class grid for MaxEnt grid search"),
    ("numero total de combinacoes RM x FC", "total number of RM x FC combinations"),
    ("Coluna de longitude: '%s' | Coluna de latitude: '%s'",
     "Longitude column: '%s' | Latitude column: '%s'"),
    ("Registros de ocorrencia: %d", "Occurrence records: %d"),
    ("Coluna 'type' encontrada. Usando %d pontos de background definidos.",
     "Column 'type' found. Using %d defined background points."),
    ("coluna 'type' presente no CSV define pontos de background",
     "column 'type' in CSV defines background points"),
    ("Valores de RM  : %s", "RM values  : %s"),
    ("Valores de FC  : %s", "FC values  : %s"),
    ("Total de modelos: %d", "Total models: %d"),
    ("tolerancia acima de 0.10 conforme Anderson et al. 2010",
     "tolerance above 0.10 per Anderson et al. 2010"),
    ("Ajustando modelo final: RM = %s | FC = %s", "Fitting final model: RM = %s | FC = %s"),
    ("RM do modelo de melhor desempenho no criterio OR_AICc",
     "RM of best-performing model by OR_AICc criterion"),
    ("FC do modelo de melhor desempenho no criterio OR_AICc",
     "FC of best-performing model by OR_AICc criterion"),

    # Spatial prioritization
    ("contents of directory de features.", "contents of features directory."),
    ("%d features com soma zero excluidas: %s",
     "%d features with zero sum excluded: %s"),
    ("extensao espacial dos rasters de features.",
     "spatial extent of feature rasters."),
    ("CSV de alvos malformado ou proporcao invalida.",
     "malformed targets CSV or invalid proportion."),
    ("Solver falhou para cenario '%s': %s. Retornando NULL.",
     "Solver failed for scenario '%s': %s. Returning NULL."),
    ("Menos de 3 cenarios BLM resolvidos. Grafico de cotovelo pode ser insuficiente para selecao de BLM.",
     "Fewer than 3 BLM scenarios solved. Elbow plot may be insufficient for BLM selection."),
    ("falha do solver ou alvos fora do intervalo [0, 0.999].",
     "solver failure or targets outside range [0, 0.999]."),
    ("Solucoes insuficientes para analise de portfolio (%d). Sao necessarias pelo menos 2.",
     "Insufficient solutions for portfolio analysis (%d). At least 2 are required."),
    ("solucoes incompativeis (extensoes diferentes) ou falha na soma de rasters.",
     "incompatible solutions (different extents) or raster sum failure."),
    ("consistencia espacial das solucoes individuais.",
     "spatial consistency of individual solutions."),
    ("Numero muito baixo de unidades de planejamento validas (%d). Check a mascara de NA no raster pu.",
     "Very low number of valid planning units (%d). Check the NA mask in the pu raster."),
    ("features do not overlap\u00adem a area de planejamento.",
     "features do not overlap with the planning area."),
    ("extensao e CRS dos rasters de features vs pu_raster.",
     "extent and CRS of feature rasters vs pu_raster."),
    ("arquivos .tif em features_dir e compatibilidade com pu_raster.",
     ".tif files in features_dir and compatibility with pu_raster."),
    ("Alvo not found para %d features; usando padrao 0.30: %s",
     "Target not found for %d features; using default 0.30: %s"),
    ("%d features com alvo > 90%%. Alvos muito altos podem tornar o problema inviavel.",
     "%d features with target > 90%%. Very high targets may make the problem infeasible."),
    ("CSV de alvos malformado ou proporcao invalida fora de [0,1].",
     "malformed targets CSV or invalid proportion outside [0,1]."),
    ("incompatibilidade entre rasters, alvos invalidos ou pacote prioritizr desatualizado.",
     "incompatibility between rasters, invalid targets, or outdated prioritizr package."),
    ("versoes de prioritizr e terra, e compatibilidade espacial dos rasters.",
     "prioritizr and terra versions, and spatial compatibility of rasters."),
    ("HiGHS falhou: %s. Tentando fallback para lpsymphony...",
     "HiGHS failed: %s. Trying fallback to lpsymphony..."),
    ("problema inviavel (alvos inalcancaveis), solver not installed, ou timeout.",
     "infeasible problem (unreachable targets), solver not installed, or timeout."),
    ("alvos vs disponibilidade de features, e instalacao do HiGHS/lpsymphony.",
     "targets vs feature availability, and HiGHS/lpsymphony installation."),
    ("Mais de 80%% das PUs selecionadas (%.1f%%). Alvos podem ser muito altos ou study area muito restrita.",
     "More than 80%% of PUs selected (%.1f%%). Targets may be too high or study area too restricted."),
    ("permissoes de escrita ou solucao invalida.",
     "write permissions or invalid solution."),
    ("output_dir e resultado do solver.", "output_dir and solver result."),
    ("incompatibilidade entre problema e solucao, ou falha na avaliacao.",
     "incompatibility between problem and solution, or evaluation failure."),
    ("objetos p e s e versao do prioritizr.", "objects p and s and prioritizr version."),
    ("falha na avaliacao de custo ou permissoes de escrita.",
     "cost evaluation failure or write permissions."),
    ("objetos p e s e output_dir.", "objects p and s and output_dir."),
    ("falha na avaliacao de raridade ou permissoes de escrita.",
     "rarity evaluation failure or write permissions."),

    # Collinearity check
    ("CSV file missing, malformado ou sem colunas numericas.",
     "CSV file missing, malformed, or without numeric columns."),
    ("caminho e formato do CSV de preditores.", "path and format of predictor CSV."),
    ("%d pares de preditores altamente correlacionados (|r| > 0.70) detectados. Reducao de colinearidade necessaria.",
     "%d highly correlated predictor pairs (|r| > 0.70) detected. Collinearity reduction required."),
    ("matriz singular, preditores constantes, ou falha no pacote usdm.",
     "singular matrix, constant predictors, or usdm package failure."),
    ("variancia de cada preditor e instalacao do pacote usdm.",
     "variance of each predictor and usdm package installation."),
    ("permissoes de escrita ou output directory inexistente.",
     "write permissions or non-existent output directory."),
    ("output_dir e permissoes do sistema de arquivos.",
     "output_dir and filesystem permissions."),

    # PVA
    ("malformed CSV file ou permissoes de leitura.",
     "malformed CSV file or read permissions."),
    ("formato do CSV e caminho correto.", "CSV format and correct path."),
    ("nomes das colunas do arquivo de taxas vitais.",
     "column names in vital rates file."),
    ("indices de coluna inconsistentes ou valores NA excessivos.",
     "inconsistent column indices or excessive NA values."),
    ("integridade dos dados de taxas vitais.", "vital rates data integrity."),
    ("lambda < 0.95 (%.4f) \u2014 populacao em declinio rapido. Recomenda-se PVA estocastico e calculo de MTE.",
     "lambda < 0.95 (%.4f) \u2014 population in rapid decline. Stochastic PVA and MTE calculation recommended."),
    ("lambda < 1.0 (%.4f) \u2014 populacao em declinio (pode ser lento).",
     "lambda < 1.0 (%.4f) \u2014 population declining (may be slow)."),
    ("matriz singular ou eigenvalor complexo.", "singular matrix or complex eigenvalue."),
    ("structra da matriz de transicao e taxas vitais.",
     "structure of transition matrix and vital rates."),
    ("permissoes de escrita ou output directory inexistente.",
     "write permissions or non-existent output directory."),
    ("n_init invalido ou erro na multiplicacao de matrizes.",
     "invalid n_init or matrix multiplication error."),
    ("dimensao da matriz e valor de n_init.", "matrix dimension and n_init value."),
    ("erro no ggplot2 ou permissoes de escrita.",
     "ggplot2 error or write permissions."),
    ("instalacao do ggplot2 e output_dir.", "ggplot2 installation and output_dir."),
    ("Elementos com CV alto (> 0.30) detectados (%d) \u2014 PVA estocastico recomendado: %s",
     "Elements with high CV (> 0.30) detected (%d) \u2014 stochastic PVA recommended: %s"),
    ("time series too short or excessive NA values.",
     "time series too short or excessive NA values."),
    ("number oe anos no CSV de taxas vitais.", "number of years in vital rates CSV."),
    ("incorrect file format de taxas vitais.", "incorrect vital rates file format."),
    ("nomes das colunas do CSV.", "CSV column names."),
    ("malformed CSV file ou missing.", "malformed CSV file or missing."),
    ("caminho e formato do CSV de taxas vitais.", "path and format of vital rates CSV."),
    ("colunas com todos os valores NA.", "columns with all NA values."),
    ("completude dos dados de taxas vitais.", "completeness of vital rates data."),
    ("n0 (%d) <= quasi_ext (%g). A populacao comeca abaixo do limiar de quasi-extincao.",
     "n0 (%d) <= quasi_ext (%g). Population starts below quasi-extinction threshold."),
    ("matriz singular ou eigenvalores complexos na A_mean.",
     "singular matrix or complex eigenvalues in A_mean."),
    ("structra da matriz de transicao.", "structure of transition matrix."),
    ("erro na amostragem de parametros ou overflow numerico.",
     "parameter sampling error or numerical overflow."),
    ("parametros de distribuicao (mu, sig2) para cada elemento de matriz.",
     "distribution parameters (mu, sig2) for each matrix element."),
    ("vetor ext_times malformado ou output directory inacessivel.",
     "malformed ext_times vector or inaccessible output directory."),
    ("output_dir e resultados da simulacao.", "output_dir and simulation results."),
    ("Approximated as t_max/5; replace with known generation time if available",
     "Approximated as t_max/5; replace with known generation time if available"),
    ("Categoria IUCN %s detectada. Considerar medidas urgentes de conservacao.",
     "IUCN category %s detected. Consider urgent conservation measures."),
    ("curva de extincao vazia ou horizontes temporais invalidos.",
     "empty extinction curve or invalid temporal horizons."),
    ("resultados da simulacao e parametro t_max.", "simulation results and t_max parameter."),
    ("erro no calculo do MTE ou lambda_s.", "error in MTE or lambda_s calculation."),
    ("resultados da simulacao all_N e ext_times.",
     "simulation results all_N and ext_times."),
    ("erro no ggplot2 ou dados de trajetoria invalidos.",
     "ggplot2 error or invalid trajectory data."),
    ("instalacao do ggplot2 e matriz all_N.", "ggplot2 installation and all_N matrix."),
    ("erro no ggplot2 ou dados da curva de extincao invalidos.",
     "ggplot2 error or invalid extinction curve data."),
    ("instalacao do ggplot2 e ext_df.", "ggplot2 installation and ext_df."),

    # Landscape connectivity
    ("that therquivo .shp ou .gpkg existe no caminho especificado",
     "that the .shp or .gpkg file exists at the specified path"),
    ("Failed to read shapefile de manchas: %s\nProbable cause: corrupted file ou CRS invalido\nCheck: integridade do shapefile",
     "Failed to read patch shapefile: %s\nProbable cause: corrupted file or invalid CRS\nCheck: shapefile integrity"),
    ("Minimum de 3 manchas necessario para analise de conectividade. Encontradas: %d\nProbable cause: dado de entrada com poucas feicoes\nCheck: arquivo de manchas e filtros de area minima",
     "Minimum of 3 patches required for connectivity analysis. Found: %d\nProbable cause: input data with few features\nCheck: patch file and minimum area filters"),
    ("Entrada em CRS geografico. Reprojetando para UTM para calculo de distancias",
     "Input in geographic CRS. Reprojecting to UTM for distance calculation"),
    ("Paisagem altamente fragmentada: %d componentes para %d manchas; considere aumentar dmax_m",
     "Highly fragmented landscape: %d components for %d patches; consider increasing dmax_m"),
    ("incorrect path para DEM", "incorrect path to DEM"),
    ("existencia do arquivo .tif do DEM", "existence of the DEM .tif file"),
    ("incorrect path\nCheck: existencia do shapefile de estradas",
     "incorrect path\nCheck: existence of roads shapefile"),
    ("Failed to read CSV de resistencia: %s\nProbable cause: formato incorreto\nCheck: colunas lc_code e resistance",
     "Failed to read resistance CSV: %s\nProbable cause: incorrect format\nCheck: lc_code and resistance columns"),
    ("CSV de resistencia deve conter colunas: lc_code, resistance. Encontradas: %s\nProbable cause: CSV header incorreto\nCheck: structra do arquivo resistance_csv",
     "Resistance CSV must contain columns: lc_code, resistance. Found: %s\nProbable cause: incorrect CSV header\nCheck: structure of resistance_csv file"),
    ("Raster de cobertura: %d linhas x %d colunas, CRS: %s",
     "Land cover raster: %d rows x %d cols, CRS: %s"),
    ("Tabela de resistencia: %d classes", "Resistance table: %d classes"),
    ("Reclassificando cobertura de terra para resistencia",
     "Reclassifying land cover to resistance"),
    ("Failed in reclassificacao: %s\nProbable cause: codigos de classe no raster fora do intervalo da tabela\nCheck: consistencia entre lc_code e valores do raster",
     "Failed in reclassification: %s\nProbable cause: raster class codes outside table range\nCheck: consistency between lc_code and raster values"),
    ("%d codigos de cobertura de terra sem atribuicao de resistencia: %s",
     "%d land cover codes without resistance assignment: %s"),
    ("Adicionando resistencia baseada em declividade...", "Adding slope-based resistance..."),
    ("Resistencia de declividade gravada", "Slope resistance written"),
    ("Failed to processar DEM para declividade: %s\nProbable cause: DEM com CRS incompativel ou valores invalidos\nCheck: CRS e extensao do DEM",
     "Failed to process DEM for slope: %s\nProbable cause: DEM with incompatible CRS or invalid values\nCheck: CRS and extent of DEM"),
    ("Adicionando resistencia de proximidade a estradas...", "Adding road proximity resistance..."),
    ("Resistencia de estradas gravada", "Road resistance written"),
    ("Failed to processar shapefile de estradas: %s\nProbable cause: shapefile invalido ou CRS incompativel\nCheck: integridade do shapefile de estradas",
     "Failed to process roads shapefile: %s\nProbable cause: invalid shapefile or incompatible CRS\nCheck: roads shapefile integrity"),
    ("Resistencia minima = %g; definindo piso em 1 antes de reescalonar",
     "Minimum resistance = %g; setting floor to 1 before rescaling"),
    ("Estatisticas da superficie de resistencia:", "Resistance surface statistics:"),
    ("Mapa de resistencia salvo: %s", "Resistance map saved: %s"),

    # Geoprocessing
    ("Extensao de corte: %s", "Clip extent: %s"),
    ("Failed to cortar camada para extensao: %s. Salvando versao global.",
     "Failed to clip layer to extent: %s. Saving global version."),
    ("WorldClim: todos os 19 BIO salvo em %s", "WorldClim: all 19 BIO saved to %s"),
    ("CHELSA BIO%d cortado para extensao de estudo.", "CHELSA BIO%d clipped to study extent."),
    ("CHELSA: todos os 19 BIO processados em %s", "CHELSA: all 19 BIO processed to %s"),
    ("Download de preditores completed. Check: %s", "Predictor download completed. Check: %s"),
    ("Area de estudo carregada: CRS=%s | Feicoes=%d",
     "Study area loaded: CRS=%s | Features=%d"),
    ("CRS do stack de rasters", "CRS of raster stack"),
    ("%d ponto(s) com coordenadas NA \u2014 serao excluidos durante a vetorizacao.",
     "%d point(s) with NA coordinates \u2014 will be excluded during vectorisation."),
    ("Apenas %.1f%% dos pontos (%d/%d) possuem dados ambientais completos \u2014 muitos pontos fora da area mascarada.",
     "Only %.1f%% of points (%d/%d) have complete environmental data \u2014 many points outside masked area."),
    ("Pontos com dados ambientais completos: %d/%d (%.1f%%)",
     "Points with complete environmental data: %d/%d (%.1f%%)"),

    # Environmental time series
    ("Coluna '%s' contem %d valores NA \u2014 podem afetar calculo de baseline e minimo.",
     "Column '%s' contains %d NA values \u2014 may affect baseline and minimum calculation."),
    ("Comprimento da serie: %d | Data de disturbio: %s",
     "Series length: %d | Disturbance date: %s"),
    ("Apenas %d observacoes pos-disturbio \u2014 ajuste de curva pode ser instavel.",
     "Only %d post-disturbance observations \u2014 curve fitting may be unstable."),
    ("24 observacoes mais recentes antes do disturbio",
     "24 most recent observations before disturbance"),
    ("Janela de baseline reduzida para %d obs (esperado 24) \u2014 serie pre-disturbio curta.",
     "Baseline window reduced to %d obs (expected 24) \u2014 short pre-disturbance series."),
    ("Minimum post-disturbance: %.4f em %s", "Minimum post-disturbance: %.4f at %s"),
    ("Failed to ajustar modelo exponencial: %s \u2014 continuando apenas com modelo linear.",
     "Failed to fit exponential model: %s \u2014 continuing with linear model only."),
    ("Tempo estimado para 80%% de recuperacao: %s meses",
     "Estimated time to 80%% recovery: %s months"),
    ("NA (inclinacao negativa)", "NA (negative slope)"),
    ("Tempo estimado para 100%% de recuperacao: %s meses",
     "Estimated time to 100%% recovery: %s months"),
    ("Saidas em: %s", "Outputs in: %s"),
    ("Inclinacao de Sen: %.6f (unidades/observacao)",
     "Sen slope: %.6f (units/observation)"),
    ("Serie suficiente para BFAST (%d obs >= %d minimo). Executando...",
     "Series sufficient for BFAST (%d obs >= %d minimum). Running..."),
    ("BFAST falhou: %s \u2014 continuando sem deteccao de quebras.",
     "BFAST failed: %s \u2014 continuing without break detection."),
    ("Serie muito curta para BFAST: %d obs < %d minimo (3 ciclos completos de frequencia %d).",
     "Series too short for BFAST: %d obs < %d minimum (3 complete cycles of frequency %d)."),
    ("Desvio padrao do baseline e zero \u2014 todas as anomalias serao infinitas ou NaN.",
     "Baseline standard deviation is zero \u2014 all anomalies will be infinite or NaN."),
    ("%d observacao(oes) com anomalia |Z| > 3 detectada(s) \u2014 possiveis outliers ou eventos extremos.",
     "%d observation(s) with anomaly |Z| > 3 detected \u2014 possible outliers or extreme events."),
    ("Anomalias calculadas em relacao as primeiras %d observacoes.",
     "Anomalies computed relative to first %d observations."),

    # Ecosystem services
    ("Tabela de ES carregada: %d classes de uso do solo",
     "ES table loaded: %d land use classes"),
    ("Tabela de ES contem %d valores NA no total \u2014 correlacoes serao calculadas com 'complete.obs'.",
     "ES table contains %d NA values total \u2014 correlations will be computed with 'complete.obs'."),
    ("Indicadores de ES: %s", "ES indicators: %s"),
    ("Encerrando sem erro. Adicione mais indicadores ao CSV de entrada.",
     "Exiting without error. Add more indicators to the input CSV."),
    ("min-max [0,1] com epsilon 1e-10", "min-max [0,1] with epsilon 1e-10"),

    # Ecological impact
    ("Coluna '%s' contem %d valores NA \u2014 podem ser excluidos pela funcao de modelo.",
     "Column '%s' contains %d NA values \u2014 may be excluded by the model function."),
    ("variavel resposta fornecida pelo usuario ou padrao 'abundance'",
     "response variable provided by user or default 'abundance'"),
    ("distribuicao binomial negativa adequada para contagens de abundancia com superdispersao",
     "negative binomial distribution appropriate for overdispersed abundance counts"),
    ("Modelo ajustado com sucesso.", "Model fitted successfully."),
    ("Termo de interacao BACI (period:treatment) not found na tabela de coeficientes.",
     "BACI interaction term (period:treatment) not found in coefficients table."),
    ("pwr ou ggplot2 not installeds.", "pwr or ggplot2 not installed."),
    ("install.packages(c('pwr','ggplot2','patchwork'))",
     "install.packages(c('pwr','ggplot2','patchwork'))"),

    # Ecological data foundation
    ("path provided as args[1] or default", "path provided as args[1] or default"),
    ("path provided as args[2] or default", "path provided as args[2] or default"),
    ("Todas as required columns presentes: %s", "All required columns present: %s"),
    ("Poucos registros apos remocao de NAs (%d). Minimum recomendado para SDM: 30.",
     "Few records after NA removal (%d). Minimum recommended for SDM: 30."),
    ("%d registros flagged pelo CoordinateCleaner (%.1f%% do total).",
     "%d records flagged by CoordinateCleaner (%.1f%% of total)."),
    ("Escrever arquivos de saida", "Write output files"),
    ("Gerar relatorio de QA", "Generate QA report"),
    ("Menos de 3 argumentos fornecidos. Usando valores padrao para teste.",
     "Fewer than 3 arguments provided. Using default values for testing."),
    ("Menos de 2 argumentos fornecidos. Usando valores padrao para teste.",
     "Fewer than 2 arguments provided. Using default values for testing."),
    ("limite inferior do periodo de registros; 1950 = pos-era moderna",
     "lower bound of record period; 1950 = post-modern era"),
    ("limite superior do periodo de registros; ano corrente por padrao",
     "upper bound of record period; current year by default"),
    ("Modo batch: %d especies carregadas de %s", "Batch mode: %d species loaded from %s"),
    ("argumento e um CSV valido com coluna scientificName",
     "argument is a valid CSV with scientificName column"),
    ("CSV valido com coluna scientificName", "valid CSV with scientificName column"),
    ("Taxon key GBIF: %d para '%s'", "GBIF taxon key: %d for '%s'"),
    ("Failed to consultar contagem de registros para '%s': %s. Assumindo dataset pequeno.",
     "Failed to query record count for '%s': %s. Assuming small dataset."),
    ("Contagem aproximada de registros (sem filtros): %d",
     "Approximate record count (without filters): %d"),
    ("Todos os downloads completeds. Check: %s", "All downloads completed. Check: %s"),
    ("Todos os downloads eBird completeds. Check: %s",
     "All eBird downloads completed. Check: %s"),
    ("Todos os downloads iNaturalist completeds. Check: %s",
     "All iNaturalist downloads completed. Check: %s"),
    ("Todos os downloads IUCN completeds. Check: %s",
     "All IUCN downloads completed. Check: %s"),
    ("Todos os downloads OBIS completeds. Check: %s",
     "All OBIS downloads completed. Check: %s"),
    ("filtro temporal; 2000 equilibra tamanho de dataset e qualidade",
     "temporal filter; 2000 balances dataset size and quality"),
    ("No records found para '%s' no iNaturalist.", "No records found for '%s' in iNaturalist."),
    ("Registros apos filtro de ano (%d-%d): %d", "Records after year filter (%d-%d): %d"),
    ("IUCN Red List API v3 \u2014 requer chave em IUCN_REDLIST_KEY",
     "IUCN Red List API v3 \u2014 requires key in IUCN_REDLIST_KEY"),
    ("Categoria IUCN para '%s': %s (criterios: %s, tendencia: %s, ano: %s)",
     "IUCN category for '%s': %s (criteria: %s, trend: %s, year: %s)"),
    ("Especie '%s' e %s \u2014 dados de distribuicao podem ser restritos por razoes de seguranca.",
     "Species '%s' is %s \u2014 distribution data may be restricted for security reasons."),
    ("Failed to buscar paises de ocorrencia para '%s': %s",
     "Failed to fetch occurrence countries for '%s': %s"),
    ("Failed to buscar habitats para '%s': %s", "Failed to fetch habitats for '%s': %s"),
    ("Sem dados de ocorrencia por pais para '%s'. Criando registro sumario.",
     "No country occurrence data for '%s'. Creating summary record."),
    ("Failed to gravar habitats para '%s': %s", "Failed to write habitats for '%s': %s"),
    ("filtro temporal; 1950 cobre era moderna de registros marinhos",
     "temporal filter; 1950 covers the modern era of marine records"),
    ("No records OBIS encontrado para '%s'.", "No OBIS records found for '%s'."),
    ("Registros apos filtro de flags OBIS: %d", "Records after OBIS quality flags filter: %d"),
    ("lida de IUCN_REDLIST_KEY; nunca exibida em logs",
     "read from IUCN_REDLIST_KEY; never shown in logs"),
    ("limite inferior do periodo; 1950 = pos-era moderna",
     "lower bound of period; 1950 = post-modern era"),
    ("limite superior do periodo; ano corrente por padrao",
     "upper bound of period; current year by default"),

    # Python ecological data downloads
    ("Carregadas %d linhas, %d colunas de %s", "Loaded %d rows, %d columns from %s"),
    ("Registros com coordenadas fora do intervalo valido: %d",
     "Records with coordinates outside valid range: %d"),
    ("Registros com coordenadas zero (0,0): %d \u2014 possivelmente erros de digitacao",
     "Records with zero coordinates (0,0): %d \u2014 possibly data entry errors"),
    ("Registros com datas futuras flagged: %d", "Records with future dates flagged: %d"),
    ("No records com data futura encontrado.", "No records with future dates found."),
    ("path provided as argv[1] ou padrao", "path provided as argv[1] or default"),
    ("path provided as argv[2] ou padrao", "path provided as argv[2] or default"),
    ("Carregar dados brutos de ocorrencias", "Load raw occurrence data"),
    ("Verificacao de colunas falhou: %s", "Column verification failed: %s"),
    ("Sinalizar problemas de coordenadas", "Flag coordinate issues"),
    ("Escrever arquivos de saida e relatorio QA", "Write output files and QA report"),
    ("%d registros removidos por flags OBIS de qualidade.",
     "%d records removed by OBIS quality flags."),
    ("Buscar registros OBIS para '%s'", "Fetch OBIS records for '%s'"),
    ("Aplicar filtros de qualidade OBIS", "Apply OBIS quality filters"),
    ("Padronizar registros para schema de saida", "Standardise records to output schema"),
    ("Gravar CSV de ocorrencias", "Write occurrences CSV"),
    ("Buscar taxon key GBIF para '%s'", "Fetch GBIF taxon key for '%s'"),
    ("Pulando '%s' \u2014 nenhum taxon key GBIF encontrado.",
     "Skipping '%s' \u2014 no GBIF taxon key found."),
    ("Estimar contagem de registros para escolha do metodo de download",
     "Estimate record count for download method selection"),
    ("Executar download assincrono (occ.download) com DOI",
     "Run asynchronous download (occ.download) with DOI"),
    ("Gravar CSV de ocorrencias", "Write occurrences CSV"),
    ("No records para gravar para '%s'.", "No records to write for '%s'."),
    ("argumento e um CSV valido com coluna scientificName",
     "argument is a valid CSV with scientificName column"),
    ("Especie '%s': %d registros com coordenadas",
     "Species '%s': %d records with coordinates"),
    ("No records para '%s'.", "No records for '%s'."),
    ("Todos os processamentos eBird completeds. Check: %s",
     "All eBird processing completed. Check: %s"),
    ("Buscar observacoes iNaturalist para '%s'", "Fetch iNaturalist observations for '%s'"),
    ("No records found para '%s'.", "No records found for '%s'."),
    ("Buscar avaliacao IUCN para '%s'", "Fetch IUCN assessment for '%s'"),
    ("Buscar ocorrencias por pais para '%s'", "Fetch country occurrences for '%s'"),
    ("Buscar habitats adequados para '%s'", "Fetch suitable habitats for '%s'"),
    ("Gravar CSV de status IUCN", "Write IUCN status CSV"),
    ("lida de IUCN_REDLIST_KEY; nunca exibida em logs",
     "read from IUCN_REDLIST_KEY; never shown in logs"),
    ("Failed to buscar paises de ocorrencia para '%s': %s",
     "Failed to fetch occurrence countries for '%s': %s"),
    ("Failed to buscar habitats para '%s': %s", "Failed to fetch habitats for '%s': %s"),

    # Camera trap
    ("Total de registros: %d, Especies: %d", "Total records: %d, Species: %d"),
    ("Filtrando para a especie '%s'", "Filtering to species '%s'"),
    ("Filtrado para '%s': %d registros", "Filtered to '%s': %d records"),
    ("structra do CSV", "CSV structure"),
    ("formato yyyy-mm-dd nas colunas de data", "yyyy-mm-dd format in date columns"),
    ("Historicos de deteccao gerados para %d especies",
     "Detection histories generated for %d species"),
    ("n_eventos_independentes < 10 for '%s'", "n_independent_events < 10 for '%s'"),

    # Acoustic monitoring
    ("incompatible audio format ou invalid frequency range",
     "incompatible audio format or invalid frequency range"),
    ("formato WAV/FLAC e configuracoes de frequencia",
     "WAV/FLAC format and frequency settings"),

    # SDM Python
    ("elapid disponivel para modelagem MaxEnt.", "elapid available for MaxEnt modelling."),
    ("number oe arvores do RF definido em params.yaml",
     "number of RF trees defined in params.yaml"),
    ("tamanho minimo de no do RF definido em params.yaml",
     "minimum RF node size defined in params.yaml"),
    ("number oe arvores do BRT definido em params.yaml",
     "number of BRT trees defined in params.yaml"),
    ("taxa de aprendizado do BRT definida em params.yaml",
     "BRT learning rate defined in params.yaml"),
    ("profundidade das arvores do BRT definida em params.yaml",
     "BRT tree depth defined in params.yaml"),
    ("fracao de subamostras por arvore (BRT) definida em params.yaml",
     "BRT bag fraction defined in params.yaml"),
    ("semente global definida em params.yaml para reprodutibilidade",
     "global seed defined in params.yaml for reproducibility"),
    ("algoritmos definidos em params.yaml", "algorithms defined in params.yaml"),
    ("number oe folds definido em params.yaml", "number of folds defined in params.yaml"),
    ("Carregar dados de ocorrencia e preditores", "Load occurrence data and predictors"),
    ("Adicione o carregamento de dados para seu estudo.",
     "Add data loading for your study."),
    ("Compilar e salvar metricas de desempenho", "Compile and save performance metrics"),
    ("Desempenho de CV:\n%s", "CV performance:\n%s"),
    ("arquivo GeoTIFF valido com multiplas bandas.", "valid GeoTIFF file with multiple bands."),
    ("Failed to salvar suitability raster: %s\n  Check: permissao de escrita em %s.",
     "Failed to save suitability raster: %s\n  Check: write permission in %s."),

    # Geoprocessing Python
    ("WorldClim: 19 variaveis BIO processadas em %s",
     "WorldClim: 19 BIO variables processed to %s"),
    ("CHELSA: 19 variaveis BIO processadas em %s",
     "CHELSA: 19 BIO variables processed to %s"),
    ("ERA5-Land: verificando disponibilidade de cdsapi...",
     "ERA5-Land: checking cdsapi availability..."),
    ("Gravar metadata de preditores", "Write predictor metadata"),

    # Community ecology
    ("Species matrix contains %d NA values. These will be treated as zero by vegan.",
     "Species matrix contains %d NA values. These will be treated as zero by vegan."),

    # ── Eighth pass (residuals) ───────────────────────────────────────────────

    # Mixed EN/PT error messages with residual PT fragments
    ("Falha na predicao ensemble: %s\nProbable cause: modelos incompativeis.\nCheck: todos os modelos foram treinados com os mesmos preditores.",
     "Failed ensemble prediction: %s\nProbable cause: incompatible models.\nCheck: all models were trained with the same predictors."),
    ("Check: arquivos .tif existem em scenarios_dir.",
     "Check: .tif files exist in scenarios_dir."),
    ("Falha na projecao do cenario %s: %s\nCheck: stack tem os mesmos preditores do modelo.",
     "Failed projecting scenario %s: %s\nCheck: stack has the same predictors as the model."),
    ("Check: formato do arquivo de alvos e nomes das features.",
     "Check: targets file format and feature names."),
    ("Check: valores de targets_base e instalacao do HiGHS.",
     "Check: targets_base values and HiGHS installation."),
    ("overlap\u00adem a area de planejamento", "overlap with the planning area"),
    ("tipos de dados do CSV e resultado do na.omit.",
     "CSV data types and result of na.omit."),
    # landscape-connectivity residuals
    ("[nenhuma \u2014 etapa inicial ou saida de processamento GIS]",
     "[none \u2014 initial step or GIS processing output]"),
    ("[nenhuma – etapa inicial ou saida de processamento GIS]",
     "[none \u2014 initial step or GIS processing output]"),
    ("nenhuma \u00e2 etapa inicial", "none \u2014 initial step"),
    ("Failed to read shapefile de manchas: %s\nProbable cause: corrupted file ou CRS invalido\nCheck: integridade do shapefile",
     "Failed to read patch shapefile: %s\nProbable cause: corrupted file or invalid CRS\nCheck: shapefile integrity"),
    ("Minimum de 3 manchas necessario para analise de conectividade. Encontradas: %d\nProbable cause: dado de entrada com poucas feicoes\nCheck: arquivo de manchas e filtros de area minima",
     "Minimum of 3 patches required for connectivity analysis. Found: %d\nProbable cause: input data with few features\nCheck: patch file and minimum area filters"),
    ("Shapefile de estradas opcional not found: %s\nProbable cause: incorrect path\nCheck: existencia do shapefile de estradas",
     "Optional roads shapefile not found: %s\nProbable cause: incorrect path\nCheck: roads shapefile existence"),
    ("Failed to read CSV de resistencia: %s\nProbable cause: formato incorreto\nCheck: colunas lc_code e resistance",
     "Failed to read resistance CSV: %s\nProbable cause: incorrect format\nCheck: lc_code and resistance columns"),
    ("CSV de resistencia deve conter colunas: lc_code, resistance. Encontradas: %s\nProbable cause: CSV header incorreto\nCheck: structra do arquivo resistance_csv",
     "Resistance CSV must contain columns: lc_code, resistance. Found: %s\nProbable cause: incorrect CSV header\nCheck: resistance_csv file structure"),
    ("Failed in reclassificacao: %s\nProbable cause: codigos de classe no raster fora do intervalo da tabela\nCheck: consistencia entre lc_code e valores do raster",
     "Failed in reclassification: %s\nProbable cause: raster class codes outside table range\nCheck: consistency between lc_code and raster values"),
    ("Failed to processar DEM para declividade: %s\nProbable cause: DEM com CRS incompativel ou valores invalidos\nCheck: CRS e extensao do DEM",
     "Failed to process DEM for slope: %s\nProbable cause: DEM with incompatible CRS or invalid values\nCheck: CRS and extent of DEM"),
    ("Failed to processar shapefile de estradas: %s\nProbable cause: shapefile invalido ou CRS incompativel\nCheck: integridade do shapefile de estradas",
     "Failed to process roads shapefile: %s\nProbable cause: invalid shapefile or incompatible CRS\nCheck: roads shapefile integrity"),
    # power analysis
    ("plot de poder", "power plot"),
    # clean_occurrences - already English but flagged by Portuguese word checker
    ("path provided as args[1] or default", "path provided as args[1] or default"),
    ("path provided as args[2] or default", "path provided as args[2] or default"),
    ("path provided as argv[1] or default", "path provided as argv[1] or default"),
    ("path provided as argv[2] or default", "path provided as argv[2] or default"),
    # SDM Python
    ("Failed to salvar suitability raster: %s\n  Check: permissao de escrita em %s.",
     "Failed to save suitability raster: %s\n  Check: write permission in %s."),
    ("Desempenho de CV:\n%s", "CV performance:\n%s"),
    # Python f-string log_step bodies (translated in-place)
    ("Buscar taxon key GBIF para '", "Fetch GBIF taxon key for '"),
    ("Buscar observacoes iNaturalist para '", "Fetch iNaturalist observations for '"),
    ("Buscar avaliacao IUCN para '", "Fetch IUCN assessment for '"),
    ("Buscar ocorrencias por pais para '", "Fetch country occurrences for '"),
    ("Buscar habitats adequados para '", "Fetch suitable habitats for '"),
    ("Buscar registros OBIS para '", "Fetch OBIS records for '"),
    ("Filtrando para a especie '", "Filtering to species '"),
    ("Processando todas as especies", "Processing all species"),
    # Acoustic monitoring
    ("BirdNET falhou para %s: %s", "BirdNET failed for %s: %s"),
    ("Encontrados %d arquivos de audio", "Found %d audio files"),
    ("Executando BirdNET em cada arquivo de audio", "Running BirdNET on each audio file"),
    ("Total de deteccoes brutas: %d", "Total raw detections: %d"),
    ("Resumo de deteccoes por hora -> %s", "Hourly detection summary -> %s"),
    ("Acumulacao de especies -> %s", "Species accumulation -> %s"),
]

def translate_file(fpath: Path) -> int:
    """Apply all translations to a file. Returns number of replacements made."""
    text = fpath.read_text(encoding="utf-8", errors="replace")
    original = text
    count = 0
    for pt, en in TRANSLATIONS:
        if pt in text:
            text = text.replace(pt, en)
            count += original.count(pt)
    if text != original:
        fpath.write_text(text, encoding="utf-8")
    return count

def main():
    skills_dir = Path("skills")
    if not skills_dir.exists():
        print("ERROR: Run from the repository root (where skills/ exists)")
        return

    script_files = sorted(
        list(skills_dir.glob("**/*.R")) + list(skills_dir.glob("**/*.py"))
    )

    total_replacements = 0
    changed_files = 0
    unchanged_files = 0

    for fpath in script_files:
        n = translate_file(fpath)
        if n > 0:
            print(f"  TRANSLATED ({n:3d} strings)  {fpath}")
            total_replacements += n
            changed_files += 1
        else:
            unchanged_files += 1

    print(f"\nDone: {changed_files} files modified, {unchanged_files} unchanged")
    print(f"Total string replacements: {total_replacements}")

if __name__ == "__main__":
    main()
